# Processing of extracted trajectory data
- In this notebook we use the output of the trajectory data extraction
- We compute some additional features
- We perform a train test split for the new data and the old dataset and save it

In [1]:
import sys
import os
sys.path.append(os.path.abspath("../.."))

from processing.filtering import filter_for_players

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.spatial.distance import euclidean

from itertools import combinations

pd.set_option('display.max_columns', None)

In [2]:
# Config
basket_x = 89.25
basket_y = 25

do_filter_for_players = False

# Data loading and filtering

In [3]:
df = pd.read_csv('merged_tracking_events_v3.csv', index_col=0)
df.head()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,shooter_speed,player1_speed,player2_speed,player3_speed,player4_speed,player5_speed,player6_speed,player7_speed,player8_speed,player9_speed,player10_speed,defender_closing_speed,ball_height,ball_speed,ball_xy_speed,ACTION_TYPE,EVENTTIME,EVENT_TYPE,GAME_DATE,GAME_EVENT_ID,GAME_ID,GRID_TYPE,HTM,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,PLAYER_NAME,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,SHOT_TYPE,SHOT_ZONE_AREA,SHOT_ZONE_BASIC,SHOT_ZONE_RANGE,TEAM_ID,TEAM_NAME,VTM,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_WCTIMESTRING,event_PCTIMESTRING,event_HOMEDESCRIPTION,event_NEUTRALDESCRIPTION,event_VISITORDESCRIPTION,event_SCORE,event_SCOREMARGIN,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_NAME,event_PLAYER1_TEAM_ID,event_PLAYER1_TEAM_CITY,event_PLAYER1_TEAM_NICKNAME,event_PLAYER1_TEAM_ABBREVIATION,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_NAME,event_PLAYER2_TEAM_ID,event_PLAYER2_TEAM_CITY,event_PLAYER2_TEAM_NICKNAME,event_PLAYER2_TEAM_ABBREVIATION,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_NAME,event_PLAYER3_TEAM_ID,event_PLAYER3_TEAM_CITY,event_PLAYER3_TEAM_NICKNAME,event_PLAYER3_TEAM_ABBREVIATION,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5
0,6.0,85.45530,15.73183,1.610613e+09,67.734160,10.014925,13.395564,22.570158,0.0,0.0,0.0,194.947173,1.204715,3.675728,4.716129,7.659447,1.949346,5.247622,1.204715,5.987868,6.851004,1.997744,0.483438,-2.466791,6.63373,3.309075,1.112232,Jump Shot,502,Missed Shot,20160101,31,21500492,Shot Chart Detail,TOR,213.7631,120.9345,8,1,101107,Marvin Williams,1.0,22,1,24,0,493.76,3PT Field Goal,Right Side Center(RC),Above the Break 3,24+ ft.,1610612766,Charlotte Hornets,CHA,493.76,494.75,21500492,31,2,1,1,7:46 PM,8:22,NaN,NaN,MISS Williams 25' 3PT Jump Shot,NaN,NaN,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,77.15655,46.37631,6.63373,1.610613e+09,2449.0,87.23876,2.45552,1.610613e+09,201960.0,80.99534,42.48588,1.610613e+09,200768.0,77.31567,46.21630,1.610613e+09,201942.0,62.12506,8.82485,1.610613e+09,202685.0,76.93952,29.80414,1.610613e+09,101107.0,85.45530,15.73183,1.610613e+09,201587.0,83.43740,39.02313,1.610613e+09,202689.0,78.71261,42.94807,1.610613e+09,203469.0,82.55217,30.04419,1.610613e+09,203798.0,73.47011,21.43042,85.45530,15.73183,1.78346,-13.27631,13.395564,-8.51578,14.07231,16.448356,-23.33024,-6.90698,24.331183,-4.45996,26.75405,27.123245,-8.13963,30.48447,31.552440,-2.90313,14.31236,14.603829,-11.98519,5.69859,13.270972,-2.01790,23.29130,23.378549,-6.74269,27.21624,28.039037,85.32663,16.03268,1.60051,-13.10494,13.202314,-7.31815,13.21644,15.107270,-23.08779,-6.97100,24.117232,-4.71736,26.50671,26.923209,-7.19829,30.60355,31.438713,-2.09298,14.01809,14.173476,-11.85966,5.54400,13.091504,-2.61657,22.72641,22.876541,-4.92329,26.39709,26.852284,85.14495,16.18636,1.38681,-12.71777,12.793159,-5.98610,12.47450,13.836421,-22.93863,-6.78491,23.921032,-5.17533,26.89367,27.387105,-5.67544,30.79210,31.310766,-1.28064,13.83799,13.897122,-11.66758,5.53008,12.911786,-3.52272,22.37467,22.650285,-2.98379,26.24632,26.415380,84.97094,16.32015,1.19623,-12.28716,12.345253,-4.89617,11.78304,12.759801,-22.99144,-6.51578,23.896897,-5.81607,27.46938,28.078346,-3.77472,30.88848,31.118270,-0.71444,13.52169,13.540551,-11.60439,5.36580,12.784900,-4.58556,22.26590,22.733184,-1.35191,26.48398,26.518463,84.79175,16.39143,1.07728,-11.60797,11.657851,-3.91545,11.40881,12.061994,-23.16408,-6.21368,23.983003,-6.82461,27.82037,28.645214,-1.80018,30.91128,30.963654,-0.43519,13.08657,13.093804,-11.61667,5.18316,12.720541,-5.77152,22.21781,22.955207,-0.00420,26.98942,26.989420,84.63760,16.60006,0.92563,-10.91426,10.953441,-3.09844,10.78895,11.225051,-23.34134,-6.03239,24.108253,-7.93778,27.71551,28.829808,0.11038,31.11971,31.119906,-0.37424,12.45247,12.458092,-11.64087,4.90088,12.630458,-7.12367,22.19165,23.306995,0.83071,26.95029,26.963090
1,6.0,76.02830,27.83371,1.610613e+09,-12.096781,13.521955,12.336397,18.459343,0.0,0.0,0.0,198.160531,4.665676,1.703602,2.178302,3.701108,2.362522,3.876690,4.665676,10.300195,4.399862,2.605242,2.151094,1.217021,7.90500,10.902410,10.753507,Running Jump Shot,429,Made Shot,20160101,47,21500492,Shot Chart Detail,TOR,-224.5972,0.9426,7,1,101107,Marvin Williams,1.0,9,1,1,1,415.76,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612766,Charlotte Hornets,CHA,415.76,416.76,21500492,47,1,46,1,7:49 PM,7:09,NaN,NaN,Williams 1' Running Jump Shot (2 PTS) (Walker ...,10 - 12,2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,202689,Kemba Walker,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,89.15574,2.54028,7.90500,1.610613e+09,2449.0,61.37738,31.57621,1.610613e+09,201960.0,88.46719,1.84140,1.610613e+09,200768.0,65.49440,37.62558,1.610613e+09,201942.0,60.65639,12.60022,1.610613e+09,202685.0,88.23260,29.63420,1.610613e+09,101107.0,76.02830,27.83371,1.610613e+09,201587.0,87.00198,9.99507,1.610613e+09,202689.0,83.56058,32.64658,1.610613e+09,203469.0,86.52916,24.78890,1.610613e+09,203798.0,74.58736,14.78114,76.02830,27.83371,-10.53390,9.79187,14.382064,-14.65092,3.74250,15.121368,12.20430,1.80049,12.336397,-15.37191,-15.23349,21.641507,12.43889,-25.99231,28.815381,7.53228,4.81287,8.938622,-1.44094,-13.05257,13.131866,10.50086,-3.04481,10.933386,10.97368,-17.83864,20.943704,75.26478,27.72586,-9.25690,10.46206,13.969427,-14.61945,4.51748,15.301501,12.68872,1.95049,12.837758,-14.39660,-15.31258,21.017545,13.06236,-25.99974,29.096593,7.74990,5.39640,9.443627,-0.26080,-12.67072,12.673404,10.49413,-3.76012,11.147433,11.64065,-15.07245,19.044251,74.34372,27.64695,-7.77161,10.97340,13.446688,-14.10582,4.97726,14.958184,13.06665,1.88964,13.202579,-13.28047,-15.58897,20.478937,13.64053,-25.94957,29.316279,8.14300,6.08670,10.166433,1.17235,-12.21909,12.275201,10.71954,-4.43459,11.600609,12.12734,-12.65559,17.528158,73.35472,27.65657,-6.08928,11.25483,12.796505,-13.23314,5.09062,14.178519,13.26142,1.50163,13.346166,-11.94360,-15.92632,19.907216,14.14007,-25.87406,29.485735,8.50956,6.79452,10.889358,2.52400,-12.05347,12.314898,11.25772,-5.05792,12.341751,12.48115,-10.48878,16.303178,72.34860,27.77365,-4.33468,11.33397,12.134592,-12.17481,5.04821,13.179925,13.46699,0.63249,13.481835,-10.43190,-16.35845,19.401635,14.47237,-25.90177,29.670713,8.79686,7.32084,11.444625,3.91258,-12.08220,12.699915,12.03127,-5.13274,13.080385,12.74745,-9.08590,15.654107,71.36311,27.90103,-2.55799,11.37904,11.663013,-11.03563,5.01681,12.122438,13.55072,-0.27045,13.553419,-9.03716,-16.97236,19.228397,14.92586,-26.04076,30.015038,8.98643,7.75354,11.869006,5.15856,-12.17880,13.226258,13.21541,-4.83906,14.073506,13.26305,-7.88351,15.429136
2,6.0,64.82727,31.16184,1.610613e+09,-14.160172,25.188053,7.819142,19.528723,0.0,0.0,0.0,751.232466,1.885535,9.311324,1.152159,5.073776,2.182537,6.253521,1.885535,3.524270,3.888948,10.481665,6.209693,7.367459,6.45445,20.133698,20.125961,Jump Shot,298,Made Shot,20160101,63,21500492,Shot Chart Detail,TOR,52.4841,234.7879,4,1,101107,Marvin Williams,1.0,58,1,23,1,300.42,3PT Field Goal,Right Side Center(RC),Above the Break 3,24+ ft.,1610612766,Charlotte Hornets,CHA,300.42,301.42,21500492,63,1,1,1,7:53 PM,4:58,NaN,NaN,Williams 24' 3PT Jump Shot (5 PTS) (Zeller 1 AST),18 - 18,TIE,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,203469,Cody Zeller,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,65.77121,30.24841,6.45445,1.610613e+09,2449.0,72.51961,29.75938,1.610613e+09,201960.0,74.44212,17.30720,1.610613e+09,200768.0,83.70124,37.29186,1.610613e+09,201942.0,83.26656,15.01258,1.610613e+09,202685.0,90.09588,17.75590,1.610613e+09,101107.0,64.82727,31.16184,1.610613e+09,201587.0,57.80547,9.64448,1.610613e+09,202689.0,78.84606,47.56727,1.610613e+09,203469.0,77.66554,24.66802,1.610613e+09,203798.0,89.58950,4.38445,64.82727,31.16184,7.69234,-1.40246,7.819142,9.61485,-13.85464,16.864056,18.87397,6.13002,19.844493,18.43929,-16.14926,24.511345,25.26861,-13.40594,28.604578,12.83827,-6.49382,14.387177,14.01879,16.40543,21.579263,-7.02180,-21.51736,22.634099,24.76223,-26.77739,36.471861,64.86814,31.30880,10.00910,-2.64685,10.353159,10.71918,-14.12938,17.735281,19.44004,5.61198,20.233869,18.12482,-15.46794,23.827846,24.96388,-14.78889,29.015626,13.25016,-8.69146,15.846394,14.66592,16.42631,22.020737,-7.82818,-22.01834,23.368519,25.29117,-25.98459,36.260753,65.00171,31.49548,12.26435,-3.88265,12.864263,11.61541,-14.29470,18.418909,19.87190,4.64579,20.407738,17.89470,-14.98220,23.338522,24.53572,-16.28098,29.446084,13.31858,-11.05256,17.307330,15.24142,16.30285,22.317791,-8.66833,-22.59387,24.199647,25.59475,-24.99094,35.772033,65.35989,31.47765,13.76327,-4.68186,14.537793,11.66779,-14.44355,18.567538,19.97822,3.55196,20.291518,17.69518,-14.50333,22.879379,23.76144,-17.60698,29.573836,13.57610,-12.96113,18.769693,15.70804,16.22837,22.585449,-9.57400,-23.06140,24.969775,25.47912,-23.56381,34.705024,65.90630,31.35016,14.42752,-5.11902,15.308746,10.68856,-14.44503,17.969536,19.86355,2.46419,20.015815,17.54917,-14.25954,22.612117,23.07148,-18.61087,29.642160,14.05420,-14.66250,20.310329,15.98279,16.15216,22.723157,-10.50384,-23.51659,25.755789,25.14384,-22.18093,33.529186,66.71254,31.13022,14.16630,-5.47255,15.186601,8.68962,-14.46004,16.870159,19.39158,1.69293,19.465338,17.40809,-14.10915,22.407805,22.24451,-19.52327,29.596897,14.59270,-16.29164,21.871544,16.00646,16.08456,22.691845,-11.49301,-23.88019,26.501939,24.00443,-20.63929,31.657431
3,6.0,78.51997,33.70086,1.610613e+09,-39.038205,13.814431,4.555563,10.664654,0.0,1.0,2.0,486.400279,10.097310,6.791624,5.652487,1.253555,2.458968,2.148049,10.097310,10.564195,0.763629,4.786759,6.059395,-1.371703,3.29333,10.737271,10.353107,Driving Floating Jump Shot,285,Made Shot,20160101,201,21500492,Shot Chart Detail,TOR,81.2165,111.8782,4,2,101107,Marvin Williams,2.0,45,1,8,1,288.07,2PT Field Goal,Right Side(R),In The Paint (Non-RA),8-16 ft.,1610612766,Charlotte Hornets,CHA,288.07,289.07,21500492,201,1,101,2,8:23 PM,4:45,NaN,NaN,Williams 9' Driving Floating Jump Shot (7 PTS),48 - 46,-2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,78.06218,33.12165,3.29333,1.610613e+09,2449.0,82.34452,36.17593,1.610613e+09,201960.0,75.84457,20.88098,1.610613e+09,200768.0,84.31168,15.08382,1.610613e+09,201942.0,74.40047,28.62151,1.610613e+09,202685.0,87.46804,30.12903,1.610613e+09,101107.0,78.51997,33.70086,1.610613e+09,201587.0,74.73122,14.04127,1.610613e+09,202689.0,81.08598,2.11606,1.610613e+09,1626163.0,90.86686,35.02705,1.610613e+09,203798.0,60.98150,23.77322,78.51997,33.70086,3.82455,2.47507,4.555563,8.94807,-3.57183,9.634621,-4.11950,-5.07935,6.539884,-2.67540,-12.81988,13.096071,5.79171,-18.61704,19.497130,12.34689,1.32619,12.417909,-17.53847,-9.92764,20.153312,-3.78875,-19.65959,20.021341,2.56601,-31.58480,31.688862,78.58110,35.93381,3.54641,2.68641,4.449025,8.63401,-5.16154,10.059206,-4.57159,-6.93292,8.304506,-4.01062,-13.79423,14.365440,5.97648,-20.38638,21.244359,12.15496,-0.14757,12.155856,-17.72332,-11.42201,21.085027,-6.06683,-22.82512,23.617632,3.17897,-33.92197,34.070602,79.39174,37.78655,3.23046,2.46664,4.064503,7.46152,-6.27122,9.746922,-5.36984,-8.50792,10.060809,-5.94648,-14.31998,15.505562,5.36729,-21.86349,22.512663,11.02651,-0.91271,11.064220,-18.62492,-12.35229,22.348752,-9.05001,-25.41306,26.976403,2.57858,-35.82984,35.922507,80.49488,39.56043,3.03209,1.68137,3.467070,6.08203,-7.32175,9.518357,-6.61622,-9.85517,11.870078,-7.93613,-15.30483,17.240069,4.44661,-23.33942,23.759227,9.50715,-1.59043,9.639262,-19.58306,-13.06066,23.538842,-12.35163,-27.66753,30.299422,1.45443,-37.57283,37.600970,82.08537,40.92010,3.08521,0.48770,3.123519,4.51139,-8.58937,9.702057,-8.46311,-10.82474,13.740423,-10.11598,-16.36905,19.242631,2.92974,-24.58336,24.757321,7.31754,-1.94878,7.572591,-20.75042,-12.94150,24.455313,-15.90332,-29.25725,33.300184,-0.22553,-38.90397,38.904624,83.61135,42.42058,3.02814,-0.98353,3.183860,3.31875,-10.21195,10.737692,-10.13293,-11.51952,15.341956,-11.97167,-17.76210,21.419922,1.30827,-26.24049,26.273083,5.32211,-3.01460,6.116590,-21.47265,-12.69949,24.946979,-19.18318,-30.71370,36.212232,-1.76443,-40.36855,40.407091
4,6.0,79.45158,17.14905,1.610613e+09,38.703331,12.555734,6.629064,13.572728,0.0,0.0,1.0,522.367370,13.110019,3.039238,15.736555,4.471107,11.992808,11.606220,13.110019,1.077040,3.374164,5.477721,5.868425,16.024389,3.53788,14.049192,13.444516,Hook Shot,227,Made Shot,20160101,213,21500492,Shot Chart Detail,TOR,-80.5516,89.6068,3,2,101107,Marvin Williams,2.0,47,1,7,1,230.50,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612766,Charlotte Hornets,CHA,230.50,231.50,21500492,213,1,55,2,8:25 PM,3:47,NaN,NaN,Williams 8' Hook Shot (9 PTS) (Batum 3 AST),50 - 48,-2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,201587,Nicolas Batum,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,80.28932,16.94484,3.53788,1.610613e+09,2449.0,85.23450,20.38978,1.610613e+09,201960.0,63.62820,33.09987,1.610613e+09,200768.0,86.69220,29.65742,1.610613e+09,201942.0,84.84322,1.52255,1.610613e+09,202685.0,79.48484,24.93224,1.610613e+09,101107.0,79.45158,17.14905,1.610613e+09,201587.0,79.96933,4.10200,1.610613e+09,202689.0,70.65765,21.60912,1.610613e+09,203087.0,83.31356,37.29335,1.610613e+09,1626163.0,50.41203,23.14616,79.45158,17.14905,5.39164,-15.62650,16.530496,0.03326,7.78319,7.783261,7.24062,12.50837,14.452885,5.78292,3.24073,6.629064,-15.82338,15.95082,22.467933,-8.79393,4.46007,9.860296,0.51775,-13.04705,13.057319,-29.03955,5.99711,29.652332,3.86198,20.14430,20.511161,77.09317,16.17925,6.70603,-13.18672,14.793932,0.30517,9.08974,9.094861,9.13060,13.05849,15.933989,8.87042,4.50430,9.948521,-16.43763,17.69504,24.151814,-4.78606,5.82340,7.537795,3.15610,-12.21849,12.619527,-28.79188,6.93375,29.615017,6.54135,20.37810,21.402248,74.68680,15.13110,7.64380,-10.15416,12.709628,0.60098,10.48678,10.503986,10.91376,13.60789,17.443762,12.07464,5.75871,13.377581,-17.06387,19.09578,25.609070,-1.03313,7.31424,7.386844,5.66021,-11.61780,12.923283,-26.69288,11.76528,29.170733,8.64680,21.25417,22.945738,72.23867,14.24042,8.44130,-7.18004,11.081901,0.85946,11.27335,11.306064,12.56209,14.01402,18.820172,15.05740,7.16624,16.675740,-17.71283,20.22220,26.882740,2.01619,8.59536,8.828660,8.06288,-11.00665,13.643914,-21.88682,12.66237,25.285737,9.93287,22.73296,24.808252,69.73276,13.51178,9.34040,-4.48628,10.361939,0.81836,11.52358,11.552602,14.14395,14.26798,20.090460,17.93144,8.34369,19.777606,-18.48659,21.11524,28.064343,4.29489,9.84289,10.739114,10.44783,-10.47050,14.791502,-17.11345,13.43921,21.759654,10.75407,24.45281,26.713104,67.16241,12.58299,9.96168,-1.88207,10.137912,0.72039,12.03777,12.059306,15.65202,14.84874,21.574773,20.50629,9.62658,22.653454,-19.19064,22.10287,29.271446,6.08979,11.18328,12.733864,12.77948,-9.55768,15.958207,-12.39035,14.49109,19.066003,11.05915,26.72951,28.927003

In [4]:
df.info(max_cols=200, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 84465 entries, 0 to 84464
Columns: 306 entries, shooter_slot to attacker4_dist_t5
dtypes: float64(255), int64(22), object(29)
memory usage: 197.8+ MB

In [5]:
df = df.dropna(subset=['shooter_x', 'shooter_y', 'shooter_speed', 'defender_closing_speed'])
#df = df.dropna(subset=['shooter_x', 'shooter_y', 'defender_closing_speed'])

In [6]:
df.info(max_cols=200, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 84103 entries, 0 to 84464
Columns: 306 entries, shooter_slot to attacker4_dist_t5
dtypes: float64(255), int64(22), object(29)
memory usage: 197.0+ MB

In [7]:
if do_filter_for_players:
    df = filter_for_players(df)
    df.info(max_cols=200, show_counts=True)

In [8]:
df['PLAYER_NAME'].unique()

array(['Marvin Williams', 'Nicolas Batum', 'Luis Scola', 'Cory Joseph',
       'Jonas Valanciunas', 'Terrence Ross', 'Frank Kaminsky',
       'DeMar DeRozan', 'Patrick Patterson', 'Brian Roberts',
       'Bismack Biyombo', 'Tyler Hansbrough', 'Kemba Walker',
       'Jeremy Lamb', 'DeMarre Carroll', 'Kyle Lowry', 'Cody Zeller',
       'PJ Hairston', 'Wesley Matthews', 'JaVale McGee',
       'Hassan Whiteside', 'Dirk Nowitzki', 'Gerald Green',
       'Zaza Pachulia', 'Deron Williams', 'Tyler Johnson', 'Dwyane Wade',
       'Udonis Haslem', 'Dwight Powell', 'Goran Dragic', 'Luol Deng',
       'Jeremy Evans', 'Raymond Felton', 'Charlie Villanueva',
       'Chandler Parsons', 'John Jenkins', 'J.J. Barea', 'Chris Bosh',
       'Chris Andersen', 'Jerian Grant', 'Kevin Seraphin', 'Bobby Portis',
       'Taj Gibson', 'Tony Snell', 'Aaron Brooks', 'Jimmy Butler',
       'Doug McDermott', 'Nikola Mirotic', 'Langston Galloway',
       'Derrick Williams', 'Kirk Hinrich', 'Sasha Vujacic', 'Robin Lopez',
       'Cameron Bairstow', 'Pau Gasol', 'Jose Calderon', 'Arron Afflalo',
       'Carmelo Anthony', "E'Twaun Moore", "Kyle O'Quinn",
       'Kristaps Porzingis', 'Lance Thomas', 'Elfrid Payton',
       'Nikola Vucevic', 'Evan Fournier', 'Andrew Nicholson',
       'Victor Oladipo', 'Drew Gooden', 'Mario Hezonja', 'Channing Frye',
       'John Wall', 'Dewayne Dedmon', 'Jason Smith', 'Otto Porter Jr.',
       'Kelly Oubre Jr.', 'Garrett Temple', 'Marcin Gortat',
       'Kris Humphries', 'Tobias Harris', 'Ramon Sessions',
       'Jared Dudley', 'Aaron Gordon', 'Willie Reed', 'Jared Sullinger',
       'Avery Bradley', 'Marcus Smart', 'Isaiah Thomas', 'Donald Sloan',
       'Joe Johnson', 'David Lee', 'Bojan Bogdanovic', 'Tyler Zeller',
       'Kelly Olynyk', 'Jarrett Jack', 'Evan Turner', 'Brook Lopez',
       'Shane Larkin', 'Amir Johnson', 'Jonas Jerebko', 'Jae Crowder',
       'Wayne Ellington', 'Thaddeus Young', 'Klay Thompson',
       'Danilo Gallinari', 'Darrell Arthur', 'Jameer Nelson',
       'Stephen Curry', 'Shaun Livingston', 'Andre Iguodala',
       'Mike Miller', 'Will Barton', 'Gary Harris', 'Marreese Speights',
       'Kenneth Faried', 'Jusuf Nurkic', 'Randy Foye', 'Draymond Green',
       'Andrew Bogut', 'Jason Thompson', 'Ian Clark', 'Myles Turner',
       'CJ Miles', 'Brandon Jennings', 'Lavoy Allen', 'Stanley Johnson',
       'Jordan Hill', 'George Hill', 'Monta Ellis', 'Aron Baynes',
       'Andre Drummond', 'Anthony Tolliver', 'Solomon Hill',
       'Ian Mahinmi', 'Rodney Stuckey', 'Ersan Ilyasova',
       'Kentavious Caldwell-Pope', 'Reggie Jackson', 'Paul George',
       'Marcus Morris', 'Jason Terry', 'Manu Ginobili',
       'Montrezl Harrell', 'Trevor Ariza', 'James Harden', 'Tim Duncan',
       'Jonathon Simmons', 'Clint Capela', 'Tony Parker', 'Patty Mills',
       'LaMarcus Aldridge', 'Corey Brewer', 'Patrick Beverley',
       'Dwight Howard', 'David West', 'Kawhi Leonard', 'Boban Marjanovic',
       'Terrence Jones', 'Ty Lawson', 'Danny Green', 'Boris Diaw',
       'Joe Ingles', 'Raul Neto', 'Tibor Pleiss', 'Tony Allen',
       'Gordon Hayward', 'Rodney Hood', 'Trevor Booker', 'Jeff Green',
       'Chris Johnson', 'Zach Randolph', 'Trey Burke', 'Vince Carter',
       'Courtney Lee', 'Mike Conley', 'Jeff Withey', 'Trey Lyles',
       'Marc Gasol', 'Gorgui Dieng', "Johnny O'Bryant III",
       'Andrew Wiggins', 'Greg Monroe', 'O.J. Mayo',
       'Giannis Antetokounmpo', 'Karl-Anthony Towns',
       'Michael Carter-Williams', 'Rashad Vaughn', 'Adreian Payne',
       'Tayshaun Prince', 'Ricky Rubio', 'Jerryd Bayless',
       'Khris Middleton', 'Kevin Garnett', 'John Henson', 'Zach LaVine',
       'Shabazz Muhammad', 'Tyus Jones', 'Jabari Parker', 'Toney Douglas',
       'Alonzo Gee', 'Jrue Holiday', 'Anthony Davis', 'Norris Cole',
       'Ryan Anderson', 'Eric Gordon', 'Serge Ibaka', 'Mitch McGary',
       'Kevin Durant', 'Kyle Singler', 'Enes Kanter', 'Steven Adams',
       'Russell Westbrook', 'Cameron Payne', 'Jeremy Lin',
       'Andre Roberson', 'Anthony Morrow', 'Dion Waiters', 'Troy Daniels',
       'Aaron Harrison', 'Mo Williams', 'Shabazz Napier',
       'Timofey Mozgov', 'Kevin Love', 'Anderson Varejao',
       'Tristan Thompson', 'LeBron James', 'James Jones',
       'Richard Jefferson', 'Matthew Dellavedova', 'JR Smith',
       'Kyrie Irving', 'Iman Shumpert', 'Lance Stephenson', 'Ish Smith',
       'DeAndre Jordan', 'Kendall Marshall', 'T.J. McConnell',
       'Cole Aldrich', 'Carl Landry', 'Isaiah Canaan', 'Josh Smith',
       'Wesley Johnson', 'Jerami Grant', 'Jamal Crawford',
       'Robert Covington', 'Branden Dawson', 'Pablo Prigioni',
       'Nik Stauskas', 'JaKarr Sampson', 'Chris Paul', 'Richaun Holmes',
       'Austin Rivers', 'Nerlens Noel', 'Jahlil Okafor', 'JJ Redick',
       'Luc Mbah a Moute', 'Kent Bazemore', 'Thabo Sefolosha',
       'Shelvin Mack', 'Justin Holiday', 'Jeff Teague', 'Mike Scott',
       'Edy Tavares', 'Kyle Korver', 'Al Horford', 'Lamar Patterson',
       'Paul Millsap', 'Jarell Eddie', 'Josh Richardson',
       'Justise Winslow', 'Alex Len', 'Mirza Teletovic', 'Brandon Bass',
       'Julius Randle', 'Roy Hibbert', 'Larry Nance Jr.', 'PJ Tucker',
       'Ronnie Price', 'Brandon Knight', 'Anthony Brown', 'Nick Young',
       'Tyson Chandler', 'Jordan Clarkson', "D'Angelo Russell",
       'Devin Booker', 'Archie Goodwin', 'TJ Warren', 'Lou Williams',
       'Marcelo Huertas', 'Jon Leuer', 'Thomas Robinson', 'James Young',
       'Harrison Barnes', 'Spencer Hawes', 'Brandon Rush',
       'Meyers Leonard', 'Matt Barnes', 'Allen Crabbe', 'JaMychal Green',
       'Mason Plumlee', 'Noah Vonleh', 'Damian Lillard', 'Ed Davis',
       'CJ McCollum', 'Maurice Harkless', 'Gerald Henderson',
       'Al-Farouq Aminu', 'Hollis Thompson', 'Nemanja Bjelica',
       'Andre Miller', 'Joel Anthony', 'Reggie Bullock',
       'Darrun Hilliard', 'Steve Blake', 'Darren Collison',
       'Nick Collison', 'Willie Cauley-Stein', 'Marco Belinelli',
       'Kosta Koufos', 'Ben McLemore', 'DeMarcus Cousins', 'Rudy Gay',
       'Rajon Rondo', 'James Johnson', 'Lucas Nogueira', 'Delon Wright',
       'Ryan Kelly', 'Tarik Black', 'Metta World Peace', 'Derrick Rose',
       'Dennis Schroder', 'Tim Hardaway Jr.', 'Devin Harris',
       'James Anderson', 'Quincy Acy', 'Seth Curry', 'Nene',
       'Dante Cunningham', 'Justin Anderson', 'Tyreke Evans', 'Omer Asik',
       'RJ Hunter', 'Glenn Robinson III', 'Paul Pierce', 'Tim Frazier',
       'Luis Montero', 'Norman Powell', 'Markel Brown', 'Tiago Splitter',
       'Mike Muscala', 'Kobe Bryant', 'Rudy Gobert', 'Marcus Thornton',
       'Kevin Martin', 'Nikola Pekovic', 'JJ Hickson',
       'Joffrey Lauvergne', 'Nikola Jokic', 'Festus Ezeli',
       'Pat Connaughton', 'Alexis Ajinca', "Amar'e Stoudemire",
       'Emmanuel Mudiay', 'Joe Young', 'Tyler Ennis', 'Miles Plumlee',
       'Matt Bonner', 'Sergey Karasev', 'Lou Amundson', 'Joakim Noah',
       'Chase Budinger', 'Lorenzo Brown', 'Markieff Morris',
       'Salah Mejri', 'D.J. Augustin', 'CJ Wilcox', 'Bradley Beal',
       'Omri Casspi', 'Chris Kaman', 'Leandro Barbosa', 'Damjan Rudez',
       'Devyn Marble', 'Sean Kilpatrick', 'Cristiano Felicio',
       'Kyle Anderson', 'Robert Sacre', 'Luke Babbitt', 'Jodie Meeks',
       'Kendrick Perkins', 'Jordan Adams', 'Brandan Wright',
       'Blake Griffin', 'Caron Butler', 'Cleanthony Early',
       'Damien Inglis', 'Greivis Vasquez', 'Christian Wood',
       'Terry Rozier', 'Alec Burks', 'Derrick Favors', 'C.J. Watson',
       'Rondae Hollis-Jefferson', 'Al Jefferson', 'Eric Moreland',
       'Josh McRoberts', 'Eric Bledsoe', 'James Michael McAdoo',
       'Spencer Dinwiddie', 'Bruno Caboclo', 'KJ McDaniels',
       'Cliff Alexander', 'James Ennis III', 'Sasha Kaun', 'Tony Wroten',
       'Donatas Motiejunas', 'Steve Novak', 'Jarell Martin',
       'Jordan Mickey', 'Bryce Cotton', 'Shayne Whittington'],
      dtype=object)

# Generate additional features

In [9]:
# Extract player data
p_x = df[[f"player{i}_x" for i in range(1, 11)]].to_numpy()
p_y = df[[f"player{i}_y" for i in range(1, 11)]].to_numpy()
p_ids = df[[f"player{i}_id" for i in range(1, 11)]].to_numpy()
p_teams = df[[f"player{i}_team_id" for i in range(1, 11)]].to_numpy()

# shooter data
s_x = df["shooter_x"].to_numpy()[:, np.newaxis]
s_y = df["shooter_y"].to_numpy()[:, np.newaxis]
s_id = df["PLAYER_ID"].to_numpy()[:, np.newaxis]
s_team = df["TEAM_ID"].to_numpy()[:, np.newaxis]

# helper: distance between shooter and all players
dx = p_x - s_x
dy = p_y - s_y
dist_to_players = np.sqrt(dx**2 + dy**2)

## Helpers

In [10]:
def get_nearest_teammate_dist(dist_to_players, p_teams, s_team, p_ids, s_id):
    '''Compute the distance from the shooter to the nearest teammate.'''
    mask = (p_teams == s_team) & (p_ids != s_id)
    masked_dist = np.where(mask, dist_to_players, np.inf)
    min_dist = np.min(masked_dist, axis=1)
    return np.where(min_dist == np.inf, np.nan, min_dist)

def get_defenders_between_shooter_and_basket(p_x, p_y, s_x, s_y, p_teams, s_team, bx, by):
    '''Count defenders positioned between the shooter and the basket.'''
    
    # Vector Shooter -> Basket
    vec_b_x, vec_b_y = bx - s_x, by - s_y
    norm_b_sq = vec_b_x**2 + vec_b_y**2
    
    # Vector Shooter -> all players
    vec_p_x, vec_p_y = p_x - s_x, p_y - s_y
    
    # projection and distance
    dot = vec_p_x * vec_b_x + vec_p_y * vec_b_y
    proj_rel = dot / norm_b_sq
    
    perp_dist = np.sqrt((vec_p_x - proj_rel * vec_b_x)**2 + (vec_p_y - proj_rel * vec_b_y)**2)
    
    # filter: enemy player, between shoter and basket and close to connection line
    mask = (p_teams != s_team) & (proj_rel > 0) & (proj_rel < 1) & (perp_dist < 3)
    return np.sum(mask, axis=1)

def get_detect_screen(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players):
    '''Detect whether a teammate is setting a screen near the closest defender.'''
    
    # get closest defender
    def_mask = (p_teams != s_team)
    masked_def_dist = np.where(def_mask, dist_to_players, np.inf)
    nearest_def_idx = np.argmin(masked_def_dist, axis=1)
    
    # coords of closest defendet
    rows = np.arange(len(p_x))
    dx_near, dy_near = p_x[rows, nearest_def_idx][:, np.newaxis], p_y[rows, nearest_def_idx][:, np.newaxis]
    
    # vector shooter -> nearest defender
    line_x, line_y = dx_near - s_x, dy_near - s_y
    line_norm_sq = line_x**2 + line_y**2
    line_norm_sq[line_norm_sq == 0] = 1e-9
    
    # check teammates
    vec_p_x, vec_p_y = p_x - s_x, p_y - s_y
    dot = vec_p_x * line_x + vec_p_y * line_y
    proj_rel = dot / line_norm_sq
    
    perp_dist = np.sqrt((vec_p_x - proj_rel * line_x)**2 + (vec_p_y - proj_rel * line_y)**2)
    dist_to_def = np.sqrt((p_x - dx_near)**2 + (p_y - dy_near)**2)
    
    # screen criteria: teammate between shooter and defender and not too for to the defender
    tm_mask = (p_teams == s_team) & (p_ids != s_id)
    is_between = (proj_rel > 0) & (proj_rel < 1)
    screen_found = tm_mask & is_between & (perp_dist < 2) & (dist_to_def < 5)
    
    return np.any(screen_found, axis=1).astype(int)

def get_offensive_spacing(p_x, p_y, p_teams, s_team):
    '''Compute offensive spacing as mean distances between all offensive players'''
    
    spacing = []
    for i in range(len(p_x)):
        # filter for offensive players
        off_mask = (p_teams[i] == s_team[i])
        off_coords = np.stack([p_x[i, off_mask], p_y[i, off_mask]], axis=1)
        
        if len(off_coords) < 2:
            spacing.append(np.nan)
            continue
            
        # distances for all combinations
        dists = []
        for p1, p2 in combinations(off_coords, 2):
            dists.append(np.linalg.norm(p1 - p2))
        spacing.append(np.mean(dists))
        
    return np.array(spacing)

def get_teammate_between_defender(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players):
    '''
        Check if there is a teammate between the shooter and the next defending player.
        Similar to get screening player, but without min distance to defender
    '''
    
    def_mask = (p_teams != s_team)
    masked_def_dist = np.where(def_mask, dist_to_players, np.inf)
    nearest_def_idx = np.argmin(masked_def_dist, axis=1)
    
    rows = np.arange(len(p_x))
    dx_near, dy_near = p_x[rows, nearest_def_idx][:, np.newaxis], p_y[rows, nearest_def_idx][:, np.newaxis]
    
    line_x, line_y = dx_near - s_x, dy_near - s_y
    line_norm_sq = line_x**2 + line_y**2
    line_norm_sq[line_norm_sq == 0] = 1e-9
    
    vec_p_x, vec_p_y = p_x - s_x, p_y - s_y
    proj_rel = (vec_p_x * line_x + vec_p_y * line_y) / line_norm_sq
    perp_dist = np.sqrt((vec_p_x - proj_rel * line_x)**2 + (vec_p_y - proj_rel * line_y)**2)
    
    tm_mask = (p_teams == s_team) & (p_ids != s_id)
    between = tm_mask & (proj_rel > 0) & (proj_rel < 1) & (perp_dist < 5)
    
    return np.any(between, axis=1).astype(int)

def get_players_in_paint(p_x, p_y):
    '''Get the amount of players in the paint'''
    in_paint = (p_x > 94-19) & (p_x <= 94) & (p_y > 17) & (p_y < 33)
    return np.sum(in_paint, axis=1)

# Compute new features

In [11]:
df["nearest_teammate_distance"] = get_nearest_teammate_dist(dist_to_players, p_teams, s_team, p_ids, s_id)
df["defenders_between"] = get_defenders_between_shooter_and_basket(p_x, p_y, s_x, s_y, p_teams, s_team, basket_x, basket_y)
df["has_screen"] = get_detect_screen(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players)
df["offensive_spacing"] = get_offensive_spacing(p_x, p_y, p_teams, s_team)
df["teammate_between_defender"] = get_teammate_between_defender(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players)
df["players_in_paint"] = get_players_in_paint(p_x, p_y)

# Check und export

In [12]:
df.head()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,shooter_speed,player1_speed,player2_speed,player3_speed,player4_speed,player5_speed,player6_speed,player7_speed,player8_speed,player9_speed,player10_speed,defender_closing_speed,ball_height,ball_speed,ball_xy_speed,ACTION_TYPE,EVENTTIME,EVENT_TYPE,GAME_DATE,GAME_EVENT_ID,GAME_ID,GRID_TYPE,HTM,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,PLAYER_NAME,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,SHOT_TYPE,SHOT_ZONE_AREA,SHOT_ZONE_BASIC,SHOT_ZONE_RANGE,TEAM_ID,TEAM_NAME,VTM,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_WCTIMESTRING,event_PCTIMESTRING,event_HOMEDESCRIPTION,event_NEUTRALDESCRIPTION,event_VISITORDESCRIPTION,event_SCORE,event_SCOREMARGIN,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_NAME,event_PLAYER1_TEAM_ID,event_PLAYER1_TEAM_CITY,event_PLAYER1_TEAM_NICKNAME,event_PLAYER1_TEAM_ABBREVIATION,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_NAME,event_PLAYER2_TEAM_ID,event_PLAYER2_TEAM_CITY,event_PLAYER2_TEAM_NICKNAME,event_PLAYER2_TEAM_ABBREVIATION,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_NAME,event_PLAYER3_TEAM_ID,event_PLAYER3_TEAM_CITY,event_PLAYER3_TEAM_NICKNAME,event_PLAYER3_TEAM_ABBREVIATION,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5,nearest_teammate_distance,defenders_between,has_screen,offensive_spacing,teammate_between_defender,players_in_paint
0,6.0,85.45530,15.73183,1.610613e+09,67.734160,10.014925,13.395564,22.570158,0.0,0.0,0.0,194.947173,1.204715,3.675728,4.716129,7.659447,1.949346,5.247622,1.204715,5.987868,6.851004,1.997744,0.483438,-2.466791,6.63373,3.309075,1.112232,Jump Shot,502,Missed Shot,20160101,31,21500492,Shot Chart Detail,TOR,213.7631,120.9345,8,1,101107,Marvin Williams,1.0,22,1,24,0,493.76,3PT Field Goal,Right Side Center(RC),Above the Break 3,24+ ft.,1610612766,Charlotte Hornets,CHA,493.76,494.75,21500492,31,2,1,1,7:46 PM,8:22,NaN,NaN,MISS Williams 25' 3PT Jump Shot,NaN,NaN,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,77.15655,46.37631,6.63373,1.610613e+09,2449.0,87.23876,2.45552,1.610613e+09,201960.0,80.99534,42.48588,1.610613e+09,200768.0,77.31567,46.21630,1.610613e+09,201942.0,62.12506,8.82485,1.610613e+09,202685.0,76.93952,29.80414,1.610613e+09,101107.0,85.45530,15.73183,1.610613e+09,201587.0,83.43740,39.02313,1.610613e+09,202689.0,78.71261,42.94807,1.610613e+09,203469.0,82.55217,30.04419,1.610613e+09,203798.0,73.47011,21.43042,85.45530,15.73183,1.78346,-13.27631,13.395564,-8.51578,14.07231,16.448356,-23.33024,-6.90698,24.331183,-4.45996,26.75405,27.123245,-8.13963,30.48447,31.552440,-2.90313,14.31236,14.603829,-11.98519,5.69859,13.270972,-2.01790,23.29130,23.378549,-6.74269,27.21624,28.039037,85.32663,16.03268,1.60051,-13.10494,13.202314,-7.31815,13.21644,15.107270,-23.08779,-6.97100,24.117232,-4.71736,26.50671,26.923209,-7.19829,30.60355,31.438713,-2.09298,14.01809,14.173476,-11.85966,5.54400,13.091504,-2.61657,22.72641,22.876541,-4.92329,26.39709,26.852284,85.14495,16.18636,1.38681,-12.71777,12.793159,-5.98610,12.47450,13.836421,-22.93863,-6.78491,23.921032,-5.17533,26.89367,27.387105,-5.67544,30.79210,31.310766,-1.28064,13.83799,13.897122,-11.66758,5.53008,12.911786,-3.52272,22.37467,22.650285,-2.98379,26.24632,26.415380,84.97094,16.32015,1.19623,-12.28716,12.345253,-4.89617,11.78304,12.759801,-22.99144,-6.51578,23.896897,-5.81607,27.46938,28.078346,-3.77472,30.88848,31.118270,-0.71444,13.52169,13.540551,-11.60439,5.36580,12.784900,-4.58556,22.26590,22.733184,-1.35191,26.48398,26.518463,84.79175,16.39143,1.07728,-11.60797,11.657851,-3.91545,11.40881,12.061994,-23.16408,-6.21368,23.983003,-6.82461,27.82037,28.645214,-1.80018,30.91128,30.963654,-0.43519,13.08657,13.093804,-11.61667,5.18316,12.720541,-5.77152,22.21781,22.955207,-0.00420,26.98942,26.989420,84.63760,16.60006,0.92563,-10.91426,10.953441,-3.09844,10.78895,11.225051,-23.34134,-6.03239,24.108253,-7.93778,27.71551,28.829808,0.11038,31.11971,31.119906,-0.37424,12.45247,12.458092,-11.64087,4.90088,12.630458,-7.12367,22.19165,23.306995,0.83071,26.95029,26.963090,13.270972,0,0,16.280458,0,2
1,6.0,76.02830,27.83371,1.610613e+09,-12.096781,13.521955,12.336397,18.459343,0.0,0.0,0.0,198.160531,4.665676,1.703602,2.178302,3.701108,2.362522,3.876690,4.665676,10.300195,4.399862,2.605242,2.151094,1.217021,7.90500,10.902410,10.753507,Running Jump Shot,429,Made Shot,20160101,47,21500492,Shot Chart Detail,TOR,-224.5972,0.9426,7,1,101107,Marvin Williams,1.0,9,1,1,1,415.76,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612766,Charlotte Hornets,CHA,415.76,416.76,21500492,47,1,46,1,7:49 PM,7:09,NaN,NaN,Williams 1' Running Jump Shot (2 PTS) (Walker ...,10 - 12,2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,202689,Kemba Walker,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,89.15574,2.54028,7.90500,1.610613e+09,2449.0,61.37738,31.57621,1.610613e+09,201960.0,88.46719,1.84140,1.610613e+09,200768.0,65.49440,37.62558,1.610613e+09,201942.0,60.65639,12.60022,1.610613e+09,202685.0,88.23260,29.63420,1.610613e+09,101107.0,76.02830,27.83371,1.610613e+09,201587.0,87.00198,9.99507,1.610613e+09,202689.0,83.56058,32.64658,1.610613e+09,203469.0,86.52916,24.78890,1.610613e+09,203798.0,74.58736,14.78114,76.02830,27.83371,-10.53390,9.79187,14.382064,-14.65092,3.74250,15.121368,12.20430,1.80049,12.336397,-15.37191,-15.23349,21.641507,12.43889,-25.99231,28.815381,7.53228,4.81287,8.938622,-1.44094,-13.05257,13.131866,10.50086,-3.04481,10.933386,10.97368,-17.83864,20.943704,75.26478,27.72586,-9.25690,10.46206,13.969427,-14.61945,4.51748,15.301501,12.68872,1.95049,12.837758,-14.39660,-15.31258,21.017545,13.06236,-25.99974,29.096593,7.74990,5.39640,9.443627,-0.26080,-12.67072,12.673404,10.49413,-3.76012,11.147433,11.64065,-15.07245,19.044251,74.34372,27.64695,-7.77161,10.97340,13.446688,-14.10582,4.97726,14.958184,13.06665,1.88964,13.202579,-13.28047,-15.58897,20.478937,13.64053,-25.94957,29.316279,8.14300,6.08670,10.166433,1.17235,-12.21909,12.275201,10.71954,-4.43459,11.600609,12.12734,-12.65559,17.528158,73.35472,27.65657,-6.08928,11.25483,12.796505,-13.23314,5.09062,14.178519,13.26142,1.50163,13.346166,-11.94360,-15.92632,19.907216,14.14007,-25.87406,29.485735,8.50956,6.79452,10.889358,2.52400,-12.05347,12.314898,11.25772,-5.05792,12.341751,12.48115,-10.48878,16.303178,72.34860,27.77365,-4.33468,11.33397,12.134592,-12.17481,5.04821,13.179925,13.46699,0.63249,13.481835,-10.43190,-16.35845,19.401635,14.47237,-25.90177,29.670713,8.79686,7.32084,11.444625,3.91258,-12.08220,12.699915,12.03127,-5.13274,13.080385,12.74745,-9.08590,15.654107,71.36311,27.90103,-2.55799,11.37904,11.663013,-11.03563,5.01681,12.122438,13.55072,-0.27045,13.553419,-9.03716,-16.97236,19.228397,14.92586,-26.04076,30.015038,8.98643,7.75354,11.869006,5.15856,-12.17880,13.226258,13.21541,-4.83906,14.073506,13.26305,-7.88351,15.429136,8.938622,0,0,14.893851,1,4
2,6.0,64.82727,31.16184,1.610613e+09,-14.160172,25.188053,7.819142,19.528723,0.0,0.0,0.0,751.232466,1.885535,9.311324,1.152159,5.073776,2.182537,6.253521,1.885535,3.524270,3.888948,10.481665,6.209693,7.367459,6.45445,20.133698,20.125961,Jump Shot,298,Made Shot,20160101,63,21500492,Shot Chart Detail,TOR,52.4841,234.7879,4,1,101107,Marvin Williams,1.0,58,1,23,1,300.42,3PT Field Goal,Right Side Center(RC),Above the Break 3,24+ ft.,1610612766,Charlotte Hornets,CHA,300.42,301.42,21500492,63,1,1,1,7:53 PM,4:58,NaN,NaN,Williams 24' 3PT Jump Shot (5 PTS) (Zeller 1 AST),18 - 18,TIE,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,203469,Cody Zeller,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,65.77121,30.24841,6.45445,1.610613e+09,2449.0,72.51961,29.75938,1.610613e+09,201960.0,74.44212,17.30720,1.610613e+09,200768.0,83.70124,37.29186,1.610613e+09,201942.0,83.26656,15.01258,1.610613e+09,202685.0,90.09588,17.75590,1.610613e+09,101107.0,64.82727,31.16184,1.610613e+09,201587.0,57.80547,9.64448,1.610613e+09,202689.0,78.84606,47.56727,1.610613e+09,203469.0,77.66554,24.66802,1.610613e+09,203798.0,89.58950,4.38445,64.82727,31.16184,7.69234,-1.40246,7.819142,9.61485,-13.85464,16.864056,18.87397,6.13002,19.844493,18.43929,-16.14926,24.511345,25.26861,-13.40594,28.604578,12.83827,-6.49382,14.387177,14.01879,16.40543,21.579263,-7.02180,-21.51736,22.634099,24.76223,-26.77739,36.471861,64.86814,31.30880,10.00910,-2.64685,10.353159,10.71918,-14.12938,17.735281,19.44004,5.61198,20.233869,18.12482,-15.46794,23.827846,24.96388,-14.78889,29.015626,13.25016,-8.69146,15.846394,14.66592,16.42631,22.020737,-7.82818,-22.01834,23.368519,25.29117,-25.98459,36.260753,65.00171,31.49548,12.26435,-3.88265,12.864263,11.61541,-14.29470,18.418909,19.87190,4.64579,20.407738,17.89470,-14.98220,23.338522,24.53572,-16.28098,29.446084,13.31858,-11.05256,17.307330,15.24142,16.30285,22.317791,-8.66833,-22.59387,24.199647,25.59475,-24.99094,35.772033,65.35989,31.47765,13.76327,-4.68186,14.537793,11.66779,-14.44355,18.567538,19.97822,3.55196,20.291518,17.69518,-14.50333,22.879379,23.76144,-17.60698,29.573836,13.57610,-12.96113,18.769693,15.70804,16.22837,22.585449,-9.57400,-23.06140,24.969775,25.47912,-23.56381,34.705024,65.90630,31.35016,14.42752,-5.11902,15.308746,10.68856,-14.44503,17.969536,19.86355,2.46419,20.015815,17.54917,-14.25954,22.612117,23.07148,-18.61087,29.642160,14.05420,-14.66250,20.310329,15.98279,16.15216,22.723157,-10.50384,-23.51659,25.755789,25.14384,-22.18093,33.529186,66.71254,31.13022,14.16630,-5.47255,15.186601,8.68962,-14.46004,16.870159,19.39158,1.69293,19.465338,17.40809,-14.10915,22.407805,22.24451,-19.52327,29.596897,14.59270,-16.29164,21.871544,16.00646,16.08456,22.691845,-11.49301,-23.88019,26.501939,24.00443,-20.63929,31.657431,14.387177,1,0,28.651747,0,2
3,6.0,78.51997,33.70086,1.610613e+09,-39.038205,13.814431,4.555563,10.664654,0.0,1.0,2.0,486.400279,10.097310,6.791624,5.652487,1.253555,2.458968,2.148049,10.097310,10.564195,0.763629,4.786759,6.059395,-1.371703,3.29333,10.737271,10.353107,Driving Floating Jump Shot,285,Made Shot,20160101,201,21500492,Shot Chart Detail,TOR,81.2165,111.8782,4,2,101107,Marvin Williams,2.0,45,1,8,1,288.07,2PT Field Goal,Right Side(R),In The Paint (Non-RA),8-16 ft.,1610612766,Charlotte Hornets,CHA,288.07,289.07,21500492,201,1,101,2,8:23 PM,4:45,NaN,NaN,Williams 9' Driving Floating Jump Shot (7 PTS),48 - 46,-2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,78.06218,33.12165,3.29333,1.610613e+09,2449.0,82.34452,36.17593,1.610613e+09,201960.0,75.84457,20.88098,1.610613e+09,200768.0,84.31168,15.08382,1.610613e+09,201942.0,74.40047,28.62151,1.610613e+09,202685.0,87.46804,30.12903,1.610613e+09,101107.0,78.51997,33.70086,1.610613e+09,201587.0,74.73122,14.04127,1.610613e+09,202689.0,81.08598,2.11606,1.610613e+09,1626163.0,90.86686,35.02705,1.610613e+09,203798.0,60.98150,23.77322,78.51997,33.70086,3.82455,2.47507,4.555563,8.94807,-3.57183,9.634621,-4.11950,-5.07935,6.539884,-2.67540,-12.81988,13.096071,5.79171,-18.61704,19.497130,12.34689,1.32619,12.417909,-17.53847,-9.92764,20.153312,-3.78875,-19.65959,20.021341,2.56601,-31.58480,31.688862,78.58110,35.93381,3.54641,2.68641,4.449025,8.63401,-5.16154,10.059206,-4.57159,-6.93292,8.304506,-4.01062,-13.79423,14.365440,5.97648,-20.38638,21.244359,12.15496,-0.14757,12.155856,-17.72332,-11.42201,21.085027,-6.06683,-22.82512,23.617632,3.17897,-33.92197,34.070602,79.39174,37.78655,3.23046,2.46664,4.064503,7.46152,-6.27122,9.746922,-5.36984,-8.50792,10.060809,-5.94648,-14.31998,15.505562,5.36729,-21.86349,22.512663,11.02651,-0.91271,11.064220,-18.62492,-12.35229,22.348752,-9.05001,-25.41306,26.976403,2.57858,-35.82984,35.922507,80.49488,39.56043,3.03209,1.68137,3.467070,6.08203,-7.32175,9.518357,-6.61622,-9.85517,11.870078,-7.93613,-15.30483,17.240069,4.44661,-23.33942,23.759227,9.50715,-1.59043,9.639262,-19.58306,-13.06066,23.538842,-12.35163,-27.66753,30.299422,1.45443,-37.57283,37.600970,82.08537,40.92010,3.08521,0.48770,3.123519,4.51139,-8.58937,9.702057,-8.46311,-10.82474,13.740423,-10.11598,-16.36905,19.242631,2.92974,-24.58336,24.757321,7.31754,-1.94878,7.572591,-20.75042,-12.94150,24.455313,-15.90332,-29.25725,33.300184,-0.22553,-38.90397,38.904624,83.61135,42.42058,3.02814,-0.98353,3.183860,3.31875,-10.21195,10.737692,-10.13293,-11.51952,15.341956,-11.97167,-17.76210,21.419922,1.30827,-26.24049,26.273083,5.32211,-3.01460,6.116590,-21.47265,-12.69949,24.946979,-19.18318,-30.71370,36.212232,-1.76443,-40.36855,40.407091,12.417909,1,0,23.692943,0,2
4,6.0,79.45158,17.14905,1.610613e+09,38.703331,12.555734,6.629064,13.572728,0.0,0.0,1.0,522.367370,13.110019,3.039238,15.736555,4.471107,11.992808,11.606220,13.110019,1.077040,3.374164,5.477721,5.868425,16.024389,3.53788,14.049192,13.444516,Hook Shot,227,Made Shot,20160101,213,21500492,Shot Chart Detail,TOR,-80.5516,89.6068,3,2,101107,Marvin Williams,2.0,47,1,7,1,230.50,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612766,Charlotte Hornets,CHA,230.50,231.50,21500492,213,1,55,2,8:25 PM,3:47,NaN,NaN,Williams 8' Hook Shot (9 PTS) (Batum 3 AST),50 - 48,-2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,201587,Nicolas Batum,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,80.28932,16.94484,3.53788,1.610613e+09,2449.0,85.23450,20.38978,1.610613e+09,201960.0,63.62820,33.09987,1.610613e+09,200768.0,86.69220,29.65742,1.610613e+09,201942.0,84.84322,1.52255,1.610613e+09,202685.0,79.48484,24.93224,1.610613e+09,101107.0,79.45158,17.14905,1.610613e+09,201587.0,79.96933,4.10200,1.610613e+09,202689.0,70.65765,21.60912,1.610613e+09,203087.0,83.31356,37.29335,1.610613e+09,1626163.0,50.41203,23.14616,79.45158,17.14905,5.39164,-15.62650,16.530496,0.03326,7.78319,7.783261,7.24062,12.50837,14.452885,5.78292,3.24073,6.629064,-15.82338,15.95082,22.467933,-8.79393,4.46007,9.860296,0.51775,-13.04705,13.057319,-29.03955,5.99711,29.652332,3.86198,20.14430,20.511161,77.09317,16.17925,6.70603,-13.18672,14.793932,0.30517,9.08974,9.094861,9.13060,13.05849,15.933989,8.87042,4.50430,9.948521,-16.43763,17.69504,24.151814,-4.78606,5.82340,7.537795,3.15610,-12.21849,12.619527,-28.79188,6.93375,29.615017,6.54135,20.37810,21.402248,74.68680,15.13110,7.64380,-10.15416,12.709628,0.60098,10.48678,10.503986,10.91376,13.60789,17.443762,12.07464,5.75871,13.377581,-17.06387,19.09578,25.609070,-1.03313,7.31424,7.386844,5.66021,-11.61780,12.923283,-26.69288,11.76528,29.170733,8.64680,21.25417,22.945738,72.23867,14.24042,8.44130,-7.18004,11.081901,0.85946,11.27335,11.306064,12.56209,14.01402,18.820172,15.05740,7.16624,16.675740,-17.71283,20.22220,26.882740,2.01619,8.59536,8.828660,8.06288,-11.00665,13.643914,-21.88682,12.66237,25.285737,9.93287,22.73296,24.808252,69.73276,13.51178,9.34040,-4.48628,10.361939,0.81836,11.52358,11.552602,14.14395,14.26798,20.090460,17.93144,8.34369,19.777606,-18.48659,21.11524,28.064343,4.29489,9.84289,10.739114,10.44783,-10.47050,14.791502,-17.11345,13.43921,21.759654,10.75407,24.45281,26.713104,67.16241,12.58299,9.96168,-1.88207,10.137912,0.72039,12.03777,12.059306,15.65202,14.84874,21.574773,20.50629,9.62658,22.653454,-19.19064,22.10287,29.271446,6.08979,11.18328,12.733864,12.77948,-9.55768,15.958207,-12.39035,14.49109,19.066003,11.05915,26.72951,28.927003,9.860296,1,0,23.770283,0,4

In [13]:
df.info(max_cols=350, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 84103 entries, 0 to 84464
Data columns (total 312 columns):
 #    Column                           Non-Null Count  Dtype
---   ------                           --------------  -----
 0    shooter_slot                     84103 non-null  float64
 1    shooter_x                        84103 non-null  float64
 2    shooter_y                        84103 non-null  float64
 3    shooter_team_id                  84103 non-null  float64
 4    shot_angle                       84103 non-null  float64
 5    distance_to_basket_tracking      84103 non-null  float64
 6    nearest_defender_dist            84103 non-null  float64
 7    avg_defender_dist                84103 non-null  float64
 8    defenders_within_3ft             84103 non-null  float64
 9    defenders_within_5ft             84103 non-null  float64
 10   defenders_within_7ft             84103 non-null  float64
 11   offensive_spacing_area           84103 non-null  float64
 12   shooter_speed                    84103 non-null  float64
 13   player1_speed                    83927 non-null  float64
 14   player2_speed                    84079 non-null  float64
 15   player3_speed                    84068 non-null  float64
 16   player4_speed                    84071 non-null  float64
 17   player5_speed                    84072 non-null  float64
 18   player6_speed                    84070 non-null  float64
 19   player7_speed                    84082 non-null  float64
 20   player8_speed                    84075 non-null  float64
 21   player9_speed                    84058 non-null  float64
 22   player10_speed                   83914 non-null  float64
 23   defender_closing_speed           84103 non-null  float64
 24   ball_height                      84103 non-null  float64
 25   ball_speed                       84103 non-null  float64
 26   ball_xy_speed                    84103 non-null  float64
 27   ACTION_TYPE                      84103 non-null  object
 28   EVENTTIME                        84103 non-null  int64
 29   EVENT_TYPE                       84103 non-null  object
 30   GAME_DATE                        84103 non-null  int64
 31   GAME_EVENT_ID                    84103 non-null  int64
 32   GAME_ID                          84103 non-null  int64
 33   GRID_TYPE                        84103 non-null  object
 34   HTM                              84103 non-null  object
 35   LOC_X                            84103 non-null  float64
 36   LOC_Y                            84103 non-null  float64
 37   MINUTES_REMAINING                84103 non-null  int64
 38   PERIOD                           84103 non-null  int64
 39   PLAYER_ID                        84103 non-null  int64
 40   PLAYER_NAME                      84103 non-null  object
 41   QUARTER                          84103 non-null  float64
 42   SECONDS_REMAINING                84103 non-null  int64
 43   SHOT_ATTEMPTED_FLAG              84103 non-null  int64
 44   SHOT_DISTANCE                    84103 non-null  int64
 45   SHOT_MADE_FLAG                   84103 non-null  int64
 46   SHOT_TIME                        84103 non-null  float64
 47   SHOT_TYPE                        84103 non-null  object
 48   SHOT_ZONE_AREA                   84103 non-null  object
 49   SHOT_ZONE_BASIC                  84103 non-null  object
 50   SHOT_ZONE_RANGE                  84103 non-null  object
 51   TEAM_ID                          84103 non-null  int64
 52   TEAM_NAME                        84103 non-null  object
 53   VTM                              84103 non-null  object
 54   tracking_game_clock              84103 non-null  float64
 55   tracking_game_clock_old          84103 non-null  float64
 56   event_GAME_ID                    84103 non-null  int64
 57   event_EVENTNUM                   84103 non-null  int64
 58   event_EVENTMSGTYPE               84103 non-null  int64
 59   event_EVENTMSGACTIONTYPE         84103 non-null  int64
 60   event_PERIOD                     84103 non-null  int64
 61   event_WCTIMESTRING               84103 non-null  object
 62   event_PCTIMESTRING               84103 non-null  object
 63   event_HOMEDESCRIPTION            44520 non-null  object
 64   event_NEUTRALDESCRIPTION         0 non-null      float64
 65   event_VISITORDESCRIPTION         44493 non-null  object
 66   event_SCORE                      37733 non-null  object
 67   event_SCOREMARGIN                37733 non-null  object
 68   event_PERSON1TYPE                84103 non-null  float64
 69   event_PLAYER1_ID                 84103 non-null  int64
 70   event_PLAYER1_NAME               84103 non-null  object
 71   event_PLAYER1_TEAM_ID            84103 non-null  float64
 72   event_PLAYER1_TEAM_CITY          84103 non-null  object
 73   event_PLAYER1_TEAM_NICKNAME      84103 non-null  object
 74   event_PLAYER1_TEAM_ABBREVIATION  84103 non-null  object
 75   event_PERSON2TYPE                84103 non-null  int64
 76   event_PLAYER2_ID                 84103 non-null  int64
 77   event_PLAYER2_NAME               21962 non-null  object
 78   event_PLAYER2_TEAM_ID            21962 non-null  float64
 79   event_PLAYER2_TEAM_CITY          21962 non-null  object
 80   event_PLAYER2_TEAM_NICKNAME      21962 non-null  object
 81   event_PLAYER2_TEAM_ABBREVIATION  21962 non-null  object
 82   event_PERSON3TYPE                84103 non-null  int64
 83   event_PLAYER3_ID                 84103 non-null  int64
 84   event_PLAYER3_NAME               4911 non-null   object
 85   event_PLAYER3_TEAM_ID            4911 non-null   float64
 86   event_PLAYER3_TEAM_CITY          4911 non-null   object
 87   event_PLAYER3_TEAM_NICKNAME      4911 non-null   object
 88   event_PLAYER3_TEAM_ABBREVIATION  4911 non-null   object
 89   ball_x                           84103 non-null  float64
 90   ball_y                           84103 non-null  float64
 91   ball_z                           84103 non-null  float64
 92   player1_team_id                  84103 non-null  float64
 93   player1_id                       84103 non-null  float64
 94   player1_x                        84103 non-null  float64
 95   player1_y                        84103 non-null  float64
 96   player2_team_id                  84103 non-null  float64
 97   player2_id                       84103 non-null  float64
 98   player2_x                        84103 non-null  float64
 99   player2_y                        84103 non-null  float64
 100  player3_team_id                  84103 non-null  float64
 101  player3_id                       84103 non-null  float64
 102  player3_x                        84103 non-null  float64
 103  player3_y                        84103 non-null  float64
 104  player4_team_id                  84103 non-null  float64
 105  player4_id                       84103 non-null  float64
 106  player4_x                        84103 non-null  float64
 107  player4_y                        84103 non-null  float64
 108  player5_team_id                  84103 non-null  float64
 109  player5_id                       84103 non-null  float64
 110  player5_x                        84103 non-null  float64
 111  player5_y                        84103 non-null  float64
 112  player6_team_id                  84103 non-null  float64
 113  player6_id                       84103 non-null  float64
 114  player6_x                        84103 non-null  float64
 115  player6_y                        84103 non-null  float64
 116  player7_team_id                  84103 non-null  float64
 117  player7_id                       84103 non-null  float64
 118  player7_x                        84103 non-null  float64
 119  player7_y                        84103 non-null  float64
 120  player8_team_id                  84103 non-null  float64
 121  player8_id                       84103 non-null  float64
 122  player8_x                        84103 non-null  float64
 123  player8_y                        84103 non-null  float64
 124  player9_team_id                  84103 non-null  float64
 125  player9_id                       84103 non-null  float64
 126  player9_x                        84103 non-null  float64
 127  player9_y                        84103 non-null  float64
 128  player10_team_id                 84100 non-null  float64
 129  player10_id                      84100 non-null  float64
 130  player10_x                       84100 non-null  float64
 131  player10_y                       84100 non-null  float64
 132  shooter_x_t0                     84103 non-null  float64
 133  shooter_y_t0                     84103 non-null  float64
 134  defender1_dx_t0                  84084 non-null  float64
 135  defender1_dy_t0                  84084 non-null  float64
 136  defender1_dist_t0                84084 non-null  float64
 137  defender2_dx_t0                  84073 non-null  float64
 138  defender2_dy_t0                  84073 non-null  float64
 139  defender2_dist_t0                84073 non-null  float64
 140  defender3_dx_t0                  84069 non-null  float64
 141  defender3_dy_t0                  84069 non-null  float64
 142  defender3_dist_t0                84069 non-null  float64
 143  defender4_dx_t0                  84070 non-null  float64
 144  defender4_dy_t0                  84070 non-null  float64
 145  defender4_dist_t0                84070 non-null  float64
 146  defender5_dx_t0                  83990 non-null  float64
 147  defender5_dy_t0                  83990 non-null  float64
 148  defender5_dist_t0                83990 non-null  float64
 149  attacker1_dx_t0                  84056 non-null  float64
 150  attacker1_dy_t0                  84056 non-null  float64
 151  attacker1_dist_t0                84056 non-null  float64
 152  attacker2_dx_t0                  84061 non-null  float64
 153  attacker2_dy_t0                  84061 non-null  float64
 154  attacker2_dist_t0                84061 non-null  float64
 155  attacker3_dx_t0                  84058 non-null  float64
 156  attacker3_dy_t0                  84058 non-null  float64
 157  attacker3_dist_t0                84058 non-null  float64
 158  attacker4_dx_t0                  84001 non-null  float64
 159  attacker4_dy_t0                  84001 non-null  float64
 160  attacker4_dist_t0                84001 non-null  float64
 161  shooter_x_t1                     84087 non-null  float64
 162  shooter_y_t1                     84087 non-null  float64
 163  defender1_dx_t1                  84055 non-null  float64
 164  defender1_dy_t1                  84055 non-null  float64
 165  defender1_dist_t1                84055 non-null  float64
 166  defender2_dx_t1                  84044 non-null  float64
 167  defender2_dy_t1                  84044 non-null  float64
 168  defender2_dist_t1                84044 non-null  float64
 169  defender3_dx_t1                  84038 non-null  float64
 170  defender3_dy_t1                  84038 non-null  float64
 171  defender3_dist_t1                84038 non-null  float64
 172  defender4_dx_t1                  84047 non-null  float64
 173  defender4_dy_t1                  84047 non-null  float64
 174  defender4_dist_t1                84047 non-null  float64
 175  defender5_dx_t1                  83961 non-null  float64
 176  defender5_dy_t1                  83961 non-null  float64
 177  defender5_dist_t1                83961 non-null  float64
 178  attacker1_dx_t1                  84037 non-null  float64
 179  attacker1_dy_t1                  84037 non-null  float64
 180  attacker1_dist_t1                84037 non-null  float64
 181  attacker2_dx_t1                  84035 non-null  float64
 182  attacker2_dy_t1                  84035 non-null  float64
 183  attacker2_dist_t1                84035 non-null  float64
 184  attacker3_dx_t1                  84043 non-null  float64
 185  attacker3_dy_t1                  84043 non-null  float64
 186  attacker3_dist_t1                84043 non-null  float64
 187  attacker4_dx_t1                  83977 non-null  float64
 188  attacker4_dy_t1                  83977 non-null  float64
 189  attacker4_dist_t1                83977 non-null  float64
 190  shooter_x_t2                     84084 non-null  float64
 191  shooter_y_t2                     84084 non-null  float64
 192  defender1_dx_t2                  84055 non-null  float64
 193  defender1_dy_t2                  84055 non-null  float64
 194  defender1_dist_t2                84055 non-null  float64
 195  defender2_dx_t2                  84043 non-null  float64
 196  defender2_dy_t2                  84043 non-null  float64
 197  defender2_dist_t2                84043 non-null  float64
 198  defender3_dx_t2                  84041 non-null  float64
 199  defender3_dy_t2                  84041 non-null  float64
 200  defender3_dist_t2                84041 non-null  float64
 201  defender4_dx_t2                  84051 non-null  float64
 202  defender4_dy_t2                  84051 non-null  float64
 203  defender4_dist_t2                84051 non-null  float64
 204  defender5_dx_t2                  83956 non-null  float64
 205  defender5_dy_t2                  83956 non-null  float64
 206  defender5_dist_t2                83956 non-null  float64
 207  attacker1_dx_t2                  84051 non-null  float64
 208  attacker1_dy_t2                  84051 non-null  float64
 209  attacker1_dist_t2                84051 non-null  float64
 210  attacker2_dx_t2                  84041 non-null  float64
 211  attacker2_dy_t2                  84041 non-null  float64
 212  attacker2_dist_t2                84041 non-null  float64
 213  attacker3_dx_t2                  84042 non-null  float64
 214  attacker3_dy_t2                  84042 non-null  float64
 215  attacker3_dist_t2                84042 non-null  float64
 216  attacker4_dx_t2                  83973 non-null  float64
 217  attacker4_dy_t2                  83973 non-null  float64
 218  attacker4_dist_t2                83973 non-null  float64
 219  shooter_x_t3                     84087 non-null  float64
 220  shooter_y_t3                     84087 non-null  float64
 221  defender1_dx_t3                  84064 non-null  float64
 222  defender1_dy_t3                  84064 non-null  float64
 223  defender1_dist_t3                84064 non-null  float64
 224  defender2_dx_t3                  84058 non-null  float64
 225  defender2_dy_t3                  84058 non-null  float64
 226  defender2_dist_t3                84058 non-null  float64
 227  defender3_dx_t3                  84055 non-null  float64
 228  defender3_dy_t3                  84055 non-null  float64
 229  defender3_dist_t3                84055 non-null  float64
 230  defender4_dx_t3                  84064 non-null  float64
 231  defender4_dy_t3                  84064 non-null  float64
 232  defender4_dist_t3                84064 non-null  float64
 233  defender5_dx_t3                  83965 non-null  float64
 234  defender5_dy_t3                  83965 non-null  float64
 235  defender5_dist_t3                83965 non-null  float64
 236  attacker1_dx_t3                  84060 non-null  float64
 237  attacker1_dy_t3                  84060 non-null  float64
 238  attacker1_dist_t3                84060 non-null  float64
 239  attacker2_dx_t3                  84060 non-null  float64
 240  attacker2_dy_t3                  84060 non-null  float64
 241  attacker2_dist_t3                84060 non-null  float64
 242  attacker3_dx_t3                  84063 non-null  float64
 243  attacker3_dy_t3                  84063 non-null  float64
 244  attacker3_dist_t3                84063 non-null  float64
 245  attacker4_dx_t3                  83986 non-null  float64
 246  attacker4_dy_t3                  83986 non-null  float64
 247  attacker4_dist_t3                83986 non-null  float64
 248  shooter_x_t4                     84095 non-null  float64
 249  shooter_y_t4                     84095 non-null  float64
 250  defender1_dx_t4                  84083 non-null  float64
 251  defender1_dy_t4                  84083 non-null  float64
 252  defender1_dist_t4                84083 non-null  float64
 253  defender2_dx_t4                  84080 non-null  float64
 254  defender2_dy_t4                  84080 non-null  float64
 255  defender2_dist_t4                84080 non-null  float64
 256  defender3_dx_t4                  84090 non-null  float64
 257  defender3_dy_t4                  84090 non-null  float64
 258  defender3_dist_t4                84090 non-null  float64
 259  defender4_dx_t4                  84083 non-null  float64
 260  defender4_dy_t4                  84083 non-null  float64
 261  defender4_dist_t4                84083 non-null  float64
 262  defender5_dx_t4                  83996 non-null  float64
 263  defender5_dy_t4                  83996 non-null  float64
 264  defender5_dist_t4                83996 non-null  float64
 265  attacker1_dx_t4                  84081 non-null  float64
 266  attacker1_dy_t4                  84081 non-null  float64
 267  attacker1_dist_t4                84081 non-null  float64
 268  attacker2_dx_t4                  84086 non-null  float64
 269  attacker2_dy_t4                  84086 non-null  float64
 270  attacker2_dist_t4                84086 non-null  float64
 271  attacker3_dx_t4                  84077 non-null  float64
 272  attacker3_dy_t4                  84077 non-null  float64
 273  attacker3_dist_t4                84077 non-null  float64
 274  attacker4_dx_t4                  84005 non-null  float64
 275  attacker4_dy_t4                  84005 non-null  float64
 276  attacker4_dist_t4                84005 non-null  float64
 277  shooter_x_t5                     84103 non-null  float64
 278  shooter_y_t5                     84103 non-null  float64
 279  defender1_dx_t5                  84103 non-null  float64
 280  defender1_dy_t5                  84103 non-null  float64
 281  defender1_dist_t5                84103 non-null  float64
 282  defender2_dx_t5                  84103 non-null  float64
 283  defender2_dy_t5                  84103 non-null  float64
 284  defender2_dist_t5                84103 non-null  float64
 285  defender3_dx_t5                  84103 non-null  float64
 286  defender3_dy_t5                  84103 non-null  float64
 287  defender3_dist_t5                84103 non-null  float64
 288  defender4_dx_t5                  84103 non-null  float64
 289  defender4_dy_t5                  84103 non-null  float64
 290  defender4_dist_t5                84103 non-null  float64
 291  defender5_dx_t5                  84023 non-null  float64
 292  defender5_dy_t5                  84023 non-null  float64
 293  defender5_dist_t5                84023 non-null  float64
 294  attacker1_dx_t5                  84103 non-null  float64
 295  attacker1_dy_t5                  84103 non-null  float64
 296  attacker1_dist_t5                84103 non-null  float64
 297  attacker2_dx_t5                  84103 non-null  float64
 298  attacker2_dy_t5                  84103 non-null  float64
 299  attacker2_dist_t5                84103 non-null  float64
 300  attacker3_dx_t5                  84103 non-null  float64
 301  attacker3_dy_t5                  84103 non-null  float64
 302  attacker3_dist_t5                84103 non-null  float64
 303  attacker4_dx_t5                  84034 non-null  float64
 304  attacker4_dy_t5                  84034 non-null  float64
 305  attacker4_dist_t5                84034 non-null  float64
 306  nearest_teammate_distance        84103 non-null  float64
 307  defenders_between                84103 non-null  int64
 308  has_screen                       84103 non-null  int64
 309  offensive_spacing                84103 non-null  float64
 310  teammate_between_defender        84103 non-null  int64
 311  players_in_paint                 84103 non-null  int64
dtypes: float64(257), int64(26), object(29)
memory usage: 200.8+ MB

In [14]:
df.describe()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,shooter_speed,player1_speed,player2_speed,player3_speed,player4_speed,player5_speed,player6_speed,player7_speed,player8_speed,player9_speed,player10_speed,defender_closing_speed,ball_height,ball_speed,ball_xy_speed,EVENTTIME,GAME_DATE,GAME_EVENT_ID,GAME_ID,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,TEAM_ID,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_NEUTRALDESCRIPTION,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_TEAM_ID,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_TEAM_ID,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_TEAM_ID,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5,nearest_teammate_distance,defenders_between,has_screen,offensive_spacing,teammate_between_defender,players_in_paint
count,84103.000000,84103.000000,84103.000000,8.410300e+04,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,83927.000000,84079.000000,84068.000000,84071.000000,84072.000000,84070.000000,84082.000000,84075.000000,84058.000000,83914.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,8.410300e+04,84103.000000,8.410300e+04,84103.000000,84103.000000,84103.000000,84103.000000,8.410300e+04,84103.000000,84103.000000,84103.0,84103.000000,84103.000000,84103.000000,8.410300e+04,84103.000000,84103.000000,8.410300e+04,84103.000000,84103.000000,84103.000000,84103.000000,0.0,84103.000000,8.410300e+04,8.410300e+04,84103.000000,8.410300e+04,2.196200e+04,84103.000000,8.410300e+04,4.911000e+03,84103.000000,84103.000000,84103.000000,8.410300e+04,84103.000000,84103.000000,84103.000000,8.410300e+04,8.410300e+04,84103.000000,84103.000000,8.410300e+04,8.410300e+04,84103.000000,84103.000000,8.410300e+04,8.410300e+04,84103.000000,84103.000000,8.410300e+04,8.410300e+04,84103.000000,84103.000000,8.410300e+04,8.410300e+04,84103.000000,84103.000000,8.410300e+04,8.410300e+04,84103.000000,84103.000000,8.410300e+04,8.410300e+04,84103.000000,84103.000000,8.410300e+04,8.410300e+04,84103.000000,84103.000000,8.410000e+04,8.410000e+04,84100.000000,84100.000000,84103.000000,84103.000000,84084.000000,84084.000000,84084.000000,84073.000000,84073.000000,84073.000000,84069.000000,84069.000000,84069.000000,84070.000000,84070.000000,84070.000000,83990.000000,83990.000000,83990.000000,84056.000000,84056.000000,84056.000000,84061.000000,84061.000000,84061.000000,84058.000000,84058.000000,84058.000000,84001.000000,84001.000000,84001.000000,84087.000000,84087.000000,84055.000000,84055.000000,84055.000000,84044.000000,84044.000000,84044.000000,84038.000000,84038.000000,84038.000000,84047.000000,84047.000000,84047.000000,83961.000000,83961.000000,83961.000000,84037.000000,84037.000000,84037.000000,84035.000000,84035.000000,84035.000000,84043.000000,84043.000000,84043.000000,83977.000000,83977.000000,83977.000000,84084.000000,84084.000000,84055.000000,84055.000000,84055.000000,84043.000000,84043.000000,84043.000000,84041.000000,84041.000000,84041.000000,84051.000000,84051.000000,84051.000000,83956.000000,83956.000000,83956.000000,84051.000000,84051.000000,84051.000000,84041.000000,84041.000000,84041.000000,84042.000000,84042.000000,84042.000000,83973.000000,83973.000000,83973.000000,84087.000000,84087.000000,84064.000000,84064.000000,84064.000000,84058.000000,84058.000000,84058.000000,84055.000000,84055.000000,84055.000000,84064.000000,84064.000000,84064.000000,83965.000000,83965.000000,83965.000000,84060.000000,84060.000000,84060.000000,84060.000000,84060.000000,84060.000000,84063.000000,84063.000000,84063.000000,83986.000000,83986.000000,83986.000000,84095.000000,84095.000000,84083.000000,84083.000000,84083.000000,84080.000000,84080.000000,84080.000000,84090.000000,84090.000000,84090.000000,84083.000000,84083.000000,84083.000000,83996.000000,83996.000000,83996.000000,84081.000000,84081.000000,84081.000000,84086.000000,84086.000000,84086.000000,84077.000000,84077.000000,84077.000000,84005.000000,84005.000000,84005.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84023.000000,84023.000000,84023.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84034.000000,84034.000000,84034.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000,84103.000000
mean,5.518293,77.671265,24.923750,1.610613e+09,-0.015809,16.854944,6.483959,16.880374,0.196771,0.460091,0.814906,377.352555,5.828147,4.890716,5.070163,5.133956,5.179277,5.099924,4.984341,5.061786,5.115586,5.209319,5.126581,2.613806,6.253550,11.300464,10.444716,351.846985,2.015324e+07,255.208578,2.150032e+07,-2.679860,126.113962,5.382947,2.474180,2.430333e+05,2.474180,28.870159,1.0,12.464216,0.448652,354.167492,1.610613e+09,354.167494,355.153872,2.150032e+07,255.208578,1.551348,27.434027,2.474180,NaN,4.500517,2.430333e+05,1.610613e+09,1.171599,5.853361e+04,1.610613e+09,0.262095,1.494368e+04,1.610613e+09,76.639901,24.732459,6.253550,1.610613e+09,99666.199803,78.205383,25.031152,1.610613e+09,1.569378e+05,77.832439,25.056385,1.610613e+09,1.921071e+05,77.981730,25.030083,1.610613e+09,2.324125e+05,77.904380,24.842866,1.610613e+09,5.166832e+05,78.689258,24.933403,1.610613e+09,1.016463e+05,78.094216,25.071450,1.610613e+09,1.581384e+05,77.796965,24.793985,1.610613e+09,1.945575e+05,77.882024,25.167972,1.610613e+09,2.399364e+05,77.910037,24.899428,1.610613e+09,5.324914e+05,78.776834,24.958279,77.671265,24.923750,0.512935,0.044178,8.092346,0.566263,0.122045,12.755187,0.425218,0.123513,16.973865,0.593668,-0.022814,20.992823,1.942989,-0.014423,25.588655,0.011105,0.129864,13.397171,-0.357575,0.016896,18.041147,-0.569379,0.055707,22.416551,1.235262,0.092481,27.560579,77.308636,24.943296,0.613952,0.048755,7.996692,0.692686,0.107472,12.770445,0.577045,0.114368,17.163183,0.776745,-0.033858,21.365084,2.208237,-0.029178,26.135425,0.142356,0.111660,12.973160,-0.121637,0.004136,18.011033,-0.302078,0.043857,22.656380,1.576788,0.078769,28.039263,76.876311,24.977903,0.750856,0.037439,7.838668,0.845042,0.090408,12.819531,0.770716,0.088920,17.416928,1.007539,-0.055693,21.794701,2.524721,-0.059053,26.720698,0.305451,0.089360,12.525718,0.135629,-0.007960,18.009854,0.000064,0.016229,22.936830,1.954748,0.048840,28.548134,76.418708,25.000835,0.902480,0.026173,7.672294,1.005224,0.062104,12.910505,0.981505,0.070807,17.711214,1.249289,-0.065022,22.235637,2.849033,-0.078382,27.286177,0.479475,0.065084,12.122290,0.402798,-0.017714,18.057693,0.307838,-0.006734,23.229922,2.346120,0.022818,29.030370,75.964723,25.023347,1.049672,0.015524,7.547885,1.145373,0.038836,13.030955,1.173873,0.043239,18.005828,1.483851,-0.072355,22.640635,3.172571,-0.093447,27.782414,0.632469,0.048799,11.813330,0.640090,-0.028801,18.137025,0.595873,-0.016468,23.495777,2.719148,0.007089,29.452464,75.557118,25.037087,1.173979,0.000163,7.511063,1.245609,0.023722,13.165503,1.324245,0.029200,18.265183,1.686721,-0.077554,22.972881,3.462116,-0.116317,28.175526,0.746420,0.028127,11.669656,0.818464,-0.043864,18.236369,0.833703,-0.030350,23.712716,3.043077,-0.005643,29.764799,11.828672,0.764491,0.041021,20.739853,0.110234,2.979311
std,2.866194,8.781989,11.682761,8.660497e+00,51.999922,7.974474,3.792319,4.613514,0.421428,0.627709,0.790538,198.681447,5.924966,4.845878,6.607799,6.201046,5.920866,7.379447,12.373313,5.582442,5.839978,5.791076,16.806467,5.346005,2.376478,14.771158,14.897259,207.143659,3.784869e+03,158.965709,1.864650e+02,129.154943,88.865660,3.442616,1.137195,3.320006e+05,1.137184,17.382945,0.0,9.846065,0.497359,207.287949,8.660497e+00,207.287950,207.288242,1.864650e+02,158.965709,0.497359,34.507914,1.137195,NaN,0.500003,3.320006e+05,8.660497e+00,1.987247,1.814027e+05,8.662672e+00,1.059398,1.032506e+05,8.558384e+00,8.889055,12.916322,2.376478,8.683092e+00,94594.429937,9.154650,11.937822,8.683092e+00,8.460895e+04,9.283938,11.808203,8.683092e+00,1.357950e+05,9.117542,12.009320,8.683092e+00,2.190532e+05,9.157417,12.145889,8.683138e+00,5.899926e+05,8.929639,11.460083,8.621647e+00,9.506889e+04,9.206061,12.127192,8.621647e+00,8.878102e+04,9.251298,11.902254,8.621647e+00,1.511314e+05,9.232831,12.201814,8.621647e+00,2.406827e+05,9.180580,12.063425,8.621616e+00,6.004899e+05,8.972043,11.326314,8.781989,11.682761,6.701276,7.035538,5.402231,9.656593,10.394494,6.239721,11.842325,13.868421,6.682389,13.308356,17.749905,7.198650,13.948822,22.701415,7.675435,10.243945,10.731082,6.373789,12.552548,14.824846,7.209981,13.942917,19.427864,8.346639,14.187747,25.440193,9.509758,8.812724,11.748475,6.451633,6.944067,5.125926,9.535257,10.332659,5.923692,11.850316,13.935455,6.355676,13.434796,17.955480,6.857494,14.181383,23.051377,7.367921,9.883224,10.443675,6.202930,12.450991,14.791708,7.031036,14.013618,19.588991,8.178359,14.404780,25.768817,9.370831,8.920394,11.820067,6.196009,6.845704,4.936997,9.468266,10.294190,5.656709,11.932679,14.023494,6.024629,13.636089,18.177043,6.507797,14.490581,23.391524,7.036610,9.515486,10.137385,6.042920,12.388851,14.755543,6.846127,14.140030,19.752143,7.998963,14.695374,26.078057,9.210694,9.094675,11.908915,5.959760,6.783196,4.845705,9.453740,10.296559,5.451933,12.061525,14.142929,5.725413,13.881734,18.399103,6.193955,14.817845,23.714762,6.748138,9.199200,9.856952,5.921761,12.383152,14.741727,6.688751,14.295344,19.917590,7.843873,15.001066,26.361055,9.092284,9.322012,11.998582,5.796593,6.742235,4.815501,9.487993,10.330041,5.313884,12.221273,14.278064,5.512602,14.128618,18.605527,5.948625,15.127283,23.992349,6.532212,8.975357,9.617993,5.823124,12.419770,14.749535,6.576809,14.463585,20.058724,7.735950,15.298907,26.595365,9.016982,9.582083,12.082923,5.751648,6.704832,4.795595,9.581673,10.388604,5.286883,12.400028,14.415911,5.450945,14.352196,18.787837,5.836084,15.364254,24.231761,6.431853,8.892862,9.472957,5.761541,12.514570,14.776919,6.563117,14.626076,20.174490,7.702502,15.536343,26.766579,9.007462,5.441232,0.748785,0.198340,5.455159,0.313183,1.588787
min,1.000000,47.000610,-2.563930,1.610613e+09,-179.790019,0.041402,0.000000,3.171303,0.000000,0.000000,0.000000,8.900792,0.003224,0.000000,0.003224,0.005070,0.000000,0.001595,0.002534,0.002174,0.000000,0.000000,0.006210,-73.160618,0.000000,0.079912,0.035103,0.000000,2.015103e+07,2.000000,2.150000e+07,-278.099800,-100.652600,0.000000,1.000000,7.080000e+02,1.000000,0.000000,1.0,0.000000,0.000000,0.400000,1.610613e+09,0.400000,0.880000,2.150000e+07,2.000000,1.000000,0.000000,1.000000,NaN,4.000000,7.080000e+02,1.610613e+09,0.000000,0.000000e+00,1.610613e+09,0.000000,0.000000e+00,1.610613e+09,47.001290,-2.809980,0.000000,1.610613e+09,708.000000,47.018740,-1.799210,1.610613e+09,1.889000e+03,47.021290,-2.307630,1.610613e+09,2.225000e+03,47.013420,-2.356830,1.610613e+09,2.544000e+03,47.007410,-2.131670,1.610613e+09,2.585000e+03,47.006520,-2.543300,1.610613e+09,7.080000e+02,47.036860,-2.563930,1.610613e+09,1.897000e+03,47.000610,-2.633870,1.610613e+09,2.225000e+03,47.000110,-2.299190,1.610613e+09,2.446000e+03,47.005440,-2.107520,1.610613e+09,2.564000e+03,47.003500,-2.481390,47.000610,-2.563930,-43.450690,-43.486820,0.000000,-46.051610,-42.254460,0.000000,-46.096970,-41.432260,0.000000,-47.726940,-44.894760,0.000000,-47.631420,-50.969100,0.000000,-41.225390,-46.843830,0.000000,-46.023230,-46.079080,0.000000,-50.324810,-47.881050,0.066065,-50.261950,-50.540690,0.000000,47.000350,-2.400800,-44.985670,-44.537420,0.000000,-44.745050,-41.855570,0.000000,-46.324830,-41.073430,0.000000,-47.312630,-45.196110,0.226400,-48.127270,-50.925320,0.000000,-41.658730,-46.942660,0.000000,-42.881140,-46.167500,0.091612,-47.019150,-47.990700,0.175536,-48.813020,-50.271270,0.000000,47.003230,-2.400760,-42.289480,-41.473870,0.000000,-44.854640,-38.824260,0.000000,-47.645680,-40.836560,0.000000,-47.127160,-45.223770,0.000000,-48.970800,-50.958860,0.000000,-39.299640,-46.796670,0.000000,-42.407440,-46.430090,0.108979,-46.306550,-48.131270,0.167695,-49.451180,-50.286580,0.762409,47.003190,-2.402750,-39.387200,-39.488250,0.000000,-41.912740,-37.085030,0.000000,-48.768590,-40.652770,0.000000,-47.364270,-45.415140,0.326286,-50.587000,-50.957850,1.539937,-38.531770,-46.492280,0.000000,-46.814670,-46.620140,0.247118,-46.757360,-48.232120,1.372241,-50.246160,-49.653100,0.745372,47.006220,-2.376610,-36.402180,-36.060200,0.000000,-39.075630,-38.794810,0.142033,-46.790110,-40.410810,0.000000,-48.098860,-45.672450,0.881425,-49.360440,-50.892790,2.341900,-35.811170,-47.784200,0.000000,-42.875820,-44.045450,0.000000,-48.780660,-48.249920,1.242766,-50.271620,-49.354700,1.813493,47.000370,-2.374860,-35.143260,-29.764780,0.000000,-38.861310,-34.144180,0.230211,-44.398940,-39.938670,1.728489,-48.537710,-45.801450,3.411750,-48.950450,-51.099660,5.293535,-36.325650,-36.206060,0.000000,-42.534360,-44.143590,0.000000,-50.202110,-48.159650,3.620052,-50.614850,-49.721020,5.017731,0.000000,0.000000,0.000000,4.292189,0.000000,0.000000
25%,3.000000,71.322210,16.653625,1.610613e+09,-39.724945,10.385693,3.653737,13.933560,0.000000,0.000000,0.000000,201.168600,2.286774,1.913494,1.980003,2.025439,2.039892,2.038024,1.922502,2.026554,1.996734,2.059565,2.039016,-0.616563,4.585910,6.827146,5.380203,173.000000,2.015112e+07,116.000000,2.150016e+07,-103.311150,47.531700,2.000000,1.000000,2.011440e+05,1.000000,14.000000,1.0,2.000000,0.000000,175.370000,1.610613e+09,175.370000,176.350000,2.150016e+07,116.000000,1.000000,1.000000,1.000000,NaN,4.000000,2.011440e+05,1.610613e+09,0.000000,0.000000e+00,1.610613e+09,0.000000,0.000000e+00,1.610613e+09,69.377550,14.668885,4.585910,1.610613e+09,2544.000000,72.143240,16.350145,1.610613e+09,1.011390e+05,71.624465,16.437630,1.610613e+09,2.011770e+05,71.893415,16.199430,1.610613e+09,2.019730e+05,71.783990,15.918770,1.610613e+09,2.027180e+05,72.979220,16.896795,1.610613e+09,2.544000e+03,71.973385,16.210170,1.610613e+09,1.011390e+05,71.581630,16.153770,1.610613e+09,2.011960e+05,71.724650,16.162690,1.610613e+09,2.019560e+05,71.794270,16.080405,1.610613e+09,2.027110e+05,73.113250,17.104820,71.322210,16.653625,-2.838035,-4.185892,4.192853,-5.851500,-7.165180,7.919638,-7.916740,-11.131900,12.141842,-9.070053,-15.578868,16.186417,-7.196530,-21.248130,20.597339,-6.580982,-7.654927,8.600068,-9.291960,-11.810300,12.661832,-10.733625,-16.336678,16.123899,-8.300850,-22.620300,20.404734,70.976855,16.475950,-2.788495,-4.211350,4.194323,-5.897612,-7.347930,8.317996,-8.010072,-11.420192,12.595785,-9.217920,-15.935975,16.783929,-7.170260,-21.719020,21.306491,-6.302480,-7.413410,8.293693,-9.106995,-11.912875,12.756316,-10.571255,-16.562730,16.479979,-8.214970,-22.988290,20.911933,70.393195,16.318877,-2.647360,-4.112175,4.000740,-5.962990,-7.482060,8.670592,-8.111830,-11.743500,13.179462,-9.337635,-16.443615,17.435614,-7.180327,-22.244457,22.094602,-5.936450,-7.170675,7.949469,-8.933090,-11.964970,12.886821,-10.508010,-16.857385,16.913886,-8.137110,-23.404090,21.457235,69.717545,16.165995,-2.472658,-3.960450,3.807310,-5.970637,-7.612102,8.919569,-8.225285,-12.063165,13.751438,-9.470505,-16.888283,18.118718,-7.164920,-22.693780,22.856347,-5.570300,-6.912323,7.596927,-8.787725,-12.015122,13.028139,-10.436590,-17.133180,17.284590,-8.042025,-23.774393,21.991845,69.004160,16.005710,-2.288005,-3.836535,3.712336,-6.009910,-7.712600,9.089118,-8.330612,-12.328190,14.223046,-9.532920,-17.236085,18.726543,-7.084730,-23.056558,23.481662,-5.252660,-6.697900,7.321350,-8.700072,-12.028000,13.104907,-10.387100,-17.321910,17.598962,-7.918470,-24.098940,22.443860,68.396405,15.875700,-2.162640,-3.807670,3.700394,-5.990840,-7.823665,9.219617,-8.432335,-12.476775,14.506969,-9.596400,-17.509895,19.116927,-6.998525,-23.376515,23.948608,-5.089200,-6.611990,7.209387,-8.655935,-12.079080,13.157549,-10.333555,-17.488490,17.798542,-7.810642,-24.291490,22.753168,7.717199,0.000000,0.000000,15.785951,0.000000,2.000000

In [15]:
#df.to_csv('merged_filtered_prep_20_players_v3.csv')
df.to_csv('merged_filtered_prep_all_players_v3.csv')

In [16]:
#df = pd.read_csv('merged_filtered_prep_20_players_v3.csv')
df = pd.read_csv('merged_filtered_prep_all_players_v3.csv')

In [17]:
df.shape

(84103, 313)

## Train test split of new and old data

In [18]:
# Load old dataset to make the same datasplit on both datasets
from app.data_providers import test_train_dataset
data = test_train_dataset()
X_train = data['train'].drop('SHOT_MADE_FLAG', axis=1)
y_train = data['train']['SHOT_MADE_FLAG']

X_test = data['test'].drop('SHOT_MADE_FLAG', axis=1)
y_test = data['test']['SHOT_MADE_FLAG']

df_old = pd.concat([data['train'], data['test']], axis=0)

Repo card metadata block was not found. Setting CardData to empty.

In [19]:
# GAME_DATE to year, for filtering
df_old['GAME_DATE'] = pd.to_datetime(df_old['GAME_DATE'].astype(int).astype(str),format='%Y%m%d')
df_old['year'] = df_old['GAME_DATE'].dt.year
df_old.head()

,GAME_ID_x,GAME_EVENT_ID,SHOT_TYPE,SHOT_DISTANCE,SHOT_ZONE_RANGE,SHOT_ZONE_BASIC,SHOT_ZONE_AREA,LOC_X,LOC_Y,ACTION_TYPE,HTM,VTM,GAME_DATE,TEAM_ID,PLAYER1_TEAM_ABBREVIATION,PLAYER_ID,scoreHome,scoreAway,shotResult,MINUTES_REMAINING,SECONDS_REMAINING,clock,PLAYER_NAME,PERIOD_x,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ABBREVIATION,PLAYER3_ID,PLAYER3_NAME,is_playoffs,PCTIMESTRING,SHOT_MADE_FLAG,IS_HOME,points,pointsHome,pointsAway,scoreHomeBeforeShot,scoreAwayBeforeShot,scoreMargin,scoreMarginBeforeShot,TimeRemainingInPeriod,TotalPlayedTime,TimeRemainingInGame,IsOvertime,OvertimeNumber,IsClutchTime,OPPONENT_INTERFERED,ANGLE,ANGLE_SECTOR,ABS_ANGLE,ANGLE_SIN,ANGLE_COS,MAIN_ACTION_TYPE,__index_level_0__,year
0,29600008.0,281.0,2PT Field Goal,8.0,8-16 ft.,In The Paint (Non-RA),Left Side(L),-42.0,69.0,Jump Shot,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,50,44,Missed,5.0,25.0,PT05M25.00S,Kevin Garnett,3.0,0.0,None,None,0.0,None,False,5:25,0.0,1,2,0,0,50.0,44.0,6,6.0,325,1835,1045,0,0,0,False,-31.328693,0,31.328693,0.087123,0.996198,Jump,448756,1996
1,29600008.0,168.0,1PT Free Throw,15.0,8-16 ft.,Mid-Range,Center(C),0.0,15.0,Free Throw,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,27,31,Missed,6.0,31.0,PT06M31.00S,Kevin Garnett,2.0,0.0,None,None,0.0,None,False,6:31,0.0,1,1,0,0,27.0,31.0,-4,-4.0,391,1049,1831,0,0,0,False,0.000000,0,0.000000,0.000000,1.000000,Other,448749,1996
2,29600008.0,404.0,2PT Field Goal,12.0,8-16 ft.,Mid-Range,Right Side(R),112.0,58.0,Jump Shot,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,71,70,Missed,2.0,53.0,PT02M53.00S,Kevin Garnett,4.0,0.0,None,None,0.0,None,False,2:53,0.0,1,2,0,0,71.0,70.0,1,1.0,173,2707,173,0,0,1,False,62.622297,1,62.622297,-0.208025,0.978123,Jump,448762,1996
3,29600008.0,206.0,2PT Field Goal,14.0,8-16 ft.,Mid-Range,Right Side(R),140.0,-5.0,Jump Shot,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,35,34,Missed,3.0,13.0,PT03M13.00S,Kevin Garnett,2.0,0.0,None,None,0.0,None,False,3:13,0.0,1,2,0,0,35.0,34.0,1,1.0,193,1247,1633,0,0,0,False,92.045408,2,92.045408,-0.807099,-0.590417,Jump,448751,1996
4,29600008.0,260.0,2PT Field Goal,16.0,16-24 ft.,Mid-Range,Right Side(R),151.0,67.0,Jump Shot,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,48,42,Missed,7.0,45.0,PT07M45.00S,Kevin Garnett,3.0,0.0,None,None,0.0,None,False,7:45,0.0,1,2,0,0,48.0,42.0,6,6.0,465,1695,1185,0,0,0,False,66.072727,1,66.072727,-0.099118,-0.995076,Jump,448754,1996

In [20]:
def create_match_key(df, id_cols):
    '''Create a key to match old and new games'''

    match_col = df[id_cols[0]].astype(int).astype(str) + "_"
    
    for id_col in id_cols[1:]:
        match_col = match_col + df[id_col].astype(int).astype(str) + "_"

    return match_col

df_old["match_key"] = create_match_key(df_old, ['GAME_ID_x', 'GAME_EVENT_ID'])
df["match_key"] = create_match_key(df, ['GAME_ID', 'GAME_EVENT_ID'])


old_keys = set(df_old["match_key"])
new_keys = set(df["match_key"])

intersection = old_keys & new_keys

print("OLD events:", len(old_keys))
print("NEW events:", len(new_keys))
print("OVERLAP:", len(intersection))

coverage_old = len(intersection) / len(old_keys)
coverage_new = len(intersection) / len(new_keys)

print("Coverage old -> new:", coverage_old)
print("Coverage new -> old:", coverage_new)

missing_keys = old_keys - new_keys
missing_df = df_old[df_old["match_key"].isin(missing_keys)]

OLD events: 537909
NEW events: 84103
OVERLAP: 8149
Coverage old -> new: 0.01514940259411908
Coverage new -> old: 0.09689309537115204

# Filter old and new dataframes by overlapping columns and make the same train test split for both

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
if do_filter_for_players:
    df_old["match_key"] = create_match_key(df_old, ['GAME_ID_x', 'GAME_EVENT_ID'])
    df["match_key"] = create_match_key(df, ['GAME_ID', 'GAME_EVENT_ID'])
else:
    # Only based on game id, since old data was filtered by players
    df_old["match_key"] = create_match_key(df_old, ['GAME_ID_x'])
    df["match_key"] = create_match_key(df, ['GAME_ID'])

common_uids = set(df_old["match_key"]).intersection(set(df["match_key"]))

df_old_filt = df_old[df_old["match_key"].isin(common_uids)].copy().sort_values("match_key").reset_index(drop=True)
df_new_filt = df[df["match_key"].isin(common_uids)].copy().sort_values("match_key").reset_index(drop=True)

In [26]:
df_new_filt.shape

(57510, 314)

In [27]:
# Make the same split on old and new data
uids = df_old["match_key"].drop_duplicates()

train_uids, test_uids = train_test_split(
    uids,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

train_old = df_old_filt[df_old_filt["match_key"].isin(train_uids)].copy()
test_old  = df_old_filt[df_old_filt["match_key"].isin(test_uids)].copy()

train_new = df_new_filt[df_new_filt["match_key"].isin(train_uids)].copy()
test_new  = df_new_filt[df_new_filt["match_key"].isin(test_uids)].copy()

#train_old.to_parquet("train_old_v3.parquet", index=False)
#test_old.to_parquet("test_old_v3.parquet", index=False)

#train_new.to_parquet("train_new_20_players_v3.parquet", index=False)
#test_new.to_parquet("test_new_20_players_v3.parquet", index=False)

train_new.to_parquet("train_new_all_players_v3.parquet", index=False)
test_new.to_parquet("test_new_all_players_v3.parquet", index=False)

In [28]:
train_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44403 entries, 354 to 57509
Columns: 314 entries, Unnamed: 0 to match_key
dtypes: float64(257), int64(27), object(30)
memory usage: 106.7+ MB