In [2]:
import sys
import os
sys.path.append(os.path.abspath("../.."))

from processing.filtering import filter_for_players

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.spatial.distance import euclidean

from itertools import combinations

pd.set_option('display.max_columns', None)

In [3]:
# Config
basket_x = 89.25
basket_y = 25

do_filter_for_players = True

In [4]:
df = pd.read_csv('merged_tracking_events_v2.csv', index_col=0)
df.head()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,ball_height,defender_closing_speed,ball_speed,ball_xy_speed,ACTION_TYPE,EVENTTIME,EVENT_TYPE,GAME_DATE,GAME_EVENT_ID,GAME_ID,GRID_TYPE,HTM,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,PLAYER_NAME,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,SHOT_TYPE,SHOT_ZONE_AREA,SHOT_ZONE_BASIC,SHOT_ZONE_RANGE,TEAM_ID,TEAM_NAME,VTM,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_WCTIMESTRING,event_PCTIMESTRING,event_HOMEDESCRIPTION,event_NEUTRALDESCRIPTION,event_VISITORDESCRIPTION,event_SCORE,event_SCOREMARGIN,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_NAME,event_PLAYER1_TEAM_ID,event_PLAYER1_TEAM_CITY,event_PLAYER1_TEAM_NICKNAME,event_PLAYER1_TEAM_ABBREVIATION,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_NAME,event_PLAYER2_TEAM_ID,event_PLAYER2_TEAM_CITY,event_PLAYER2_TEAM_NICKNAME,event_PLAYER2_TEAM_ABBREVIATION,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_NAME,event_PLAYER3_TEAM_ID,event_PLAYER3_TEAM_CITY,event_PLAYER3_TEAM_NICKNAME,event_PLAYER3_TEAM_ABBREVIATION,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5,shooter_speed
0,6.0,85.45530,15.73183,1.610613e+09,67.734160,10.014925,13.395564,22.570158,0.0,0.0,0.0,194.947173,6.63373,-0.325555,17.394056,14.926487,Jump Shot,502,Missed Shot,20160101,31,21500492,Shot Chart Detail,TOR,213.7631,120.9345,8,1,101107,Marvin Williams,1.0,22,1,24,0,493.76,3PT Field Goal,Right Side Center(RC),Above the Break 3,24+ ft.,1610612766,Charlotte Hornets,CHA,493.76,493.76,21500492,31,2,1,1,7:46 PM,8:22,NaN,NaN,MISS Williams 25' 3PT Jump Shot,NaN,NaN,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,77.15655,46.37631,6.63373,1.610613e+09,2449.0,87.23876,2.45552,1.610613e+09,201960.0,80.99534,42.48588,1.610613e+09,200768.0,77.31567,46.21630,1.610613e+09,201942.0,62.12506,8.82485,1.610613e+09,202685.0,76.93952,29.80414,1.610613e+09,101107.0,85.45530,15.73183,1.610613e+09,201587.0,83.43740,39.02313,1.610613e+09,202689.0,78.71261,42.94807,1.610613e+09,203469.0,82.55217,30.04419,1.610613e+09,203798.0,73.47011,21.43042,85.45530,15.73183,1.78346,-13.27631,13.395564,-8.51578,14.07231,16.448356,-23.33024,-6.90698,24.331183,-4.45996,26.75405,27.123245,-8.13963,30.48447,31.552440,-11.98519,5.69859,13.270972,-2.90313,14.31236,14.603829,-2.01790,23.29130,23.378549,-6.74269,27.21624,28.039037,85.45530,15.73183,1.78346,-13.27631,13.395564,-8.51578,14.07231,16.448356,-23.33024,-6.90698,24.331183,-4.45996,26.75405,27.123245,-8.13963,30.48447,31.552440,-11.98519,5.69859,13.270972,-2.90313,14.31236,14.603829,-2.01790,23.29130,23.378549,-6.74269,27.21624,28.039037,85.45530,15.73183,1.78346,-13.27631,13.395564,-8.51578,14.07231,16.448356,-23.33024,-6.90698,24.331183,-4.45996,26.75405,27.123245,-8.13963,30.48447,31.552440,-11.98519,5.69859,13.270972,-2.90313,14.31236,14.603829,-2.01790,23.29130,23.378549,-6.74269,27.21624,28.039037,85.45530,15.73183,1.78346,-13.27631,13.395564,-8.51578,14.07231,16.448356,-23.33024,-6.90698,24.331183,-4.45996,26.75405,27.123245,-8.13963,30.48447,31.552440,-11.98519,5.69859,13.270972,-2.90313,14.31236,14.603829,-2.01790,23.29130,23.378549,-6.74269,27.21624,28.039037,85.45530,15.73183,1.78346,-13.27631,13.395564,-8.51578,14.07231,16.448356,-23.33024,-6.90698,24.331183,-4.45996,26.75405,27.123245,-8.13963,30.48447,31.552440,-11.98519,5.69859,13.270972,-2.90313,14.31236,14.603829,-2.01790,23.29130,23.378549,-6.74269,27.21624,28.039037,85.45530,15.73183,1.78346,-13.27631,13.395564,-8.51578,14.07231,16.448356,-23.33024,-6.90698,24.331183,-4.45996,26.75405,27.123245,-8.13963,30.48447,31.552440,-11.98519,5.69859,13.270972,-2.90313,14.31236,14.603829,-2.01790,23.29130,23.378549,-6.74269,27.21624,28.039037,1.638098
1,6.0,76.02830,27.83371,1.610613e+09,-12.096781,13.521955,12.336397,18.459343,0.0,0.0,0.0,198.160531,7.90500,-2.188530,15.676120,13.712885,Running Jump Shot,429,Made Shot,20160101,47,21500492,Shot Chart Detail,TOR,-224.5972,0.9426,7,1,101107,Marvin Williams,1.0,9,1,1,1,415.76,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612766,Charlotte Hornets,CHA,415.76,415.76,21500492,47,1,46,1,7:49 PM,7:09,NaN,NaN,Williams 1' Running Jump Shot (2 PTS) (Walker ...,10 - 12,2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,202689,Kemba Walker,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,89.15574,2.54028,7.90500,1.610613e+09,2449.0,61.37738,31.57621,1.610613e+09,201960.0,88.46719,1.84140,1.610613e+09,200768.0,65.49440,37.62558,1.610613e+09,201942.0,60.65639,12.60022,1.610613e+09,202685.0,88.23260,29.63420,1.610613e+09,101107.0,76.02830,27.83371,1.610613e+09,201587.0,87.00198,9.99507,1.610613e+09,202689.0,83.56058,32.64658,1.610613e+09,203469.0,86.52916,24.78890,1.610613e+09,203798.0,74.58736,14.78114,76.02830,27.83371,12.20430,1.80049,12.336397,-10.53390,9.79187,14.382064,-14.65092,3.74250,15.121368,-15.37191,-15.23349,21.641507,12.43889,-25.99231,28.815381,7.53228,4.81287,8.938622,10.50086,-3.04481,10.933386,-1.44094,-13.05257,13.131866,10.97368,-17.83864,20.943704,76.02830,27.83371,12.20430,1.80049,12.336397,-10.53390,9.79187,14.382064,-14.65092,3.74250,15.121368,-15.37191,-15.23349,21.641507,12.43889,-25.99231,28.815381,7.53228,4.81287,8.938622,10.50086,-3.04481,10.933386,-1.44094,-13.05257,13.131866,10.97368,-17.83864,20.943704,76.02830,27.83371,12.20430,1.80049,12.336397,-10.53390,9.79187,14.382064,-14.65092,3.74250,15.121368,-15.37191,-15.23349,21.641507,12.43889,-25.99231,28.815381,7.53228,4.81287,8.938622,10.50086,-3.04481,10.933386,-1.44094,-13.05257,13.131866,10.97368,-17.83864,20.943704,76.02830,27.83371,12.20430,1.80049,12.336397,-10.53390,9.79187,14.382064,-14.65092,3.74250,15.121368,-15.37191,-15.23349,21.641507,12.43889,-25.99231,28.815381,7.53228,4.81287,8.938622,10.50086,-3.04481,10.933386,-1.44094,-13.05257,13.131866,10.97368,-17.83864,20.943704,76.02830,27.83371,12.20430,1.80049,12.336397,-10.53390,9.79187,14.382064,-14.65092,3.74250,15.121368,-15.37191,-15.23349,21.641507,12.43889,-25.99231,28.815381,7.53228,4.81287,8.938622,10.50086,-3.04481,10.933386,-1.44094,-13.05257,13.131866,10.97368,-17.83864,20.943704,76.02830,27.83371,12.20430,1.80049,12.336397,-10.53390,9.79187,14.382064,-14.65092,3.74250,15.121368,-15.37191,-15.23349,21.641507,12.43889,-25.99231,28.815381,7.53228,4.81287,8.938622,10.50086,-3.04481,10.933386,-1.44094,-13.05257,13.131866,10.97368,-17.83864,20.943704,2.110194
2,6.0,64.82727,31.16184,1.610613e+09,-14.160172,25.188053,7.819142,19.528723,0.0,0.0,0.0,751.232466,6.45445,-3.723057,17.300351,14.290179,Jump Shot,298,Made Shot,20160101,63,21500492,Shot Chart Detail,TOR,52.4841,234.7879,4,1,101107,Marvin Williams,1.0,58,1,23,1,300.42,3PT Field Goal,Right Side Center(RC),Above the Break 3,24+ ft.,1610612766,Charlotte Hornets,CHA,300.42,300.42,21500492,63,1,1,1,7:53 PM,4:58,NaN,NaN,Williams 24' 3PT Jump Shot (5 PTS) (Zeller 1 AST),18 - 18,TIE,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,203469,Cody Zeller,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,65.77121,30.24841,6.45445,1.610613e+09,2449.0,72.51961,29.75938,1.610613e+09,201960.0,74.44212,17.30720,1.610613e+09,200768.0,83.70124,37.29186,1.610613e+09,201942.0,83.26656,15.01258,1.610613e+09,202685.0,90.09588,17.75590,1.610613e+09,101107.0,64.82727,31.16184,1.610613e+09,201587.0,57.80547,9.64448,1.610613e+09,202689.0,78.84606,47.56727,1.610613e+09,203469.0,77.66554,24.66802,1.610613e+09,203798.0,89.58950,4.38445,64.82727,31.16184,7.69234,-1.40246,7.819142,9.61485,-13.85464,16.864056,18.87397,6.13002,19.844493,18.43929,-16.14926,24.511345,25.26861,-13.40594,28.604578,12.83827,-6.49382,14.387177,14.01879,16.40543,21.579263,-7.02180,-21.51736,22.634099,24.76223,-26.77739,36.471861,64.82727,31.16184,7.69234,-1.40246,7.819142,9.61485,-13.85464,16.864056,18.87397,6.13002,19.844493,18.43929,-16.14926,24.511345,25.26861,-13.40594,28.604578,12.83827,-6.49382,14.387177,14.01879,16.40543,21.579263,-7.02180,-21.51736,22.634099,24.76223,-26.77739,36.471861,64.82727,31.16184,7.69234,-1.40246,7.819142,9.61485,-13.85464,16.864056,18.87397,6.13002,19.844493,18.43929,-16.14926,24.511345,25.26861,-13.40594,28.604578,12.83827,-6.49382,14.387177,14.01879,16.40543,21.579263,-7.02180,-21.51736,22.634099,24.76223,-26.77739,36.471861,64.82727,31.16184,7.69234,-1.40246,7.819142,9.61485,-13.85464,16.864056,18.87397,6.13002,19.844493,18.43929,-16.14926,24.511345,25.26861,-13.40594,28.604578,12.83827,-6.49382,14.387177,14.01879,16.40543,21.579263,-7.02180,-21.51736,22.634099,24.76223,-26.77739,36.471861,64.82727,31.16184,7.69234,-1.40246,7.819142,9.61485,-13.85464,16.864056,18.87397,6.13002,19.844493,18.43929,-16.14926,24.511345,25.26861,-13.40594,28.604578,12.83827,-6.49382,14.387177,14.01879,16.40543,21.579263,-7.02180,-21.51736,22.634099,24.76223,-26.77739,36.471861,64.82727,31.16184,7.69234,-1.40246,7.819142,9.61485,-13.85464,16.864056,18.87397,6.13002,19.844493,18.43929,-16.14926,24.511345,25.26861,-13.40594,28.604578,12.83827,-6.49382,14.387177,14.01879,16.40543,21.579263,-7.02180,-21.51736,22.634099,24.76223,-26.77739,36.471861,1.547839
3,6.0,78.51997,33.70086,1.610613e+09,-39.038205,13.814431,4.555563,10.664654,0.0,1.0,2.0,486.400279,3.29333,-2.249731,13.552285,10.491883,Driving Floating Jump Shot,285,Made Shot,20160101,201,21500492,Shot Chart Detail,TOR,81.2165,111.8782,4,2,101107,Marvin Williams,2.0,45,1,8,1,288.07,2PT Field Goal,Right Side(R),In The Paint (Non-RA),8-16 ft.,1610612766,Charlotte Hornets,CHA,288.07,288.07,21500492,201,1,101,2,8:23 PM,4:45,NaN,NaN,Williams 9' Driving Floating Jump Shot (7 PTS),48 - 46,-2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,78.06218,33.12165,3.29333,1.610613e+09,2449.0,82.34452,36.17593,1.610613e+09,201960.0,75.84457,20.88098,1.610613e+09,200768.0,84.31168,15.08382,1.610613e+09,201942.0,74.40047,28.62151,1.610613e+09,202685.0,87.46804,30.12903,1.610613e+09,101107.0,78.51997,33.70086,1.610613e+09,201587.0,74.73122,14.04127,1.610613e+09,202689.0,81.08598,2.11606,1.610613e+09,1626163.0,90.86686,35.02705,1.610613e+09,203798.0,60.98150,23.77322,78.51997,33.70086,3.82455,2.47507,4.555563,-4.11950,-5.07935,6.539884,8.94807,-3.57183,9.634621,-2.67540,-12.81988,13.096071,5.79171,-18.61704,19.497130,12.34689,1.32619,12.417909,-3.78875,-19.65959,20.021341,-17.53847,-9.92764,20.153312,2.56601,-31.58480,31.688862,78.51997,33.70086,3.82455,2.47507,4.555563,-4.11950,-5.07935,6.539884,8.94807,-3.57183,9.634621,-2.67540,-12.81988,13.096071,5.79171,-18.61704,19.497130,12.34689,1.32619,12.417909,-3.78875,-19.65959,20.021341,-17.53847,-9.92764,20.153312,2.56601,-31.58480,31.688862,78.51997,33.70086,3.82455,2.47507,4.555563,-4.11950,-5.07935,6.539884,8.94807,-3.57183,9.634621,-2.67540,-12.81988,13.096071,5.79171,-18.61704,19.497130,12.34689,1.32619,12.417909,-3.78875,-19.65959,20.021341,-17.53847,-9.92764,20.153312,2.56601,-31.58480,31.688862,78.51997,33.70086,3.82455,2.47507,4.555563,-4.11950,-5.07935,6.539884,8.94807,-3.57183,9.634621,-2.67540,-12.81988,13.096071,5.79171,-18.61704,19.497130,12.34689,1.32619,12.417909,-3.78875,-19.65959,20.021341,-17.53847,-9.92764,20.153312,2.56601,-31.58480,31.688862,78.51997,33.70086,3.82455,2.47507,4.555563,-4.11950,-5.07935,6.539884,8.94807,-3.57183,9.634621,-2.67540,-12.81988,13.096071,5.79171,-18.61704,19.497130,12.34689,1.32619,12.417909,-3.78875,-19.65959,20.021341,-17.53847,-9.92764,20.153312,2.56601,-31.58480,31.688862,78.51997,33.70086,3.82455,2.47507,4.555563,-4.11950,-5.07935,6.539884,8.94807,-3.57183,9.634621,-2.67540,-12.81988,13.096071,5.79171,-18.61704,19.497130,12.34689,1.32619,12.417909,-3.78875,-19.65959,20.021341,-17.53847,-9.92764,20.153312,2.56601,-31.58480,31.688862,6.919631
4,6.0,79.45158,17.14905,1.610613e+09,38.703331,12.555734,6.629064,13.572728,0.0,0.0,1.0,522.367370,3.53788,-5.023420,12.534780,9.104749,Hook Shot,227,Made Shot,20160101,213,21500492,Shot Chart Detail,TOR,-80.5516,89.6068,3,2,101107,Marvin Williams,2.0,47,1,7,1,230.50,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612766,Charlotte Hornets,CHA,230.50,230.50,21500492,213,1,55,2,8:25 PM,3:47,NaN,NaN,Williams 8' Hook Shot (9 PTS) (Batum 3 AST),50 - 48,-2,5.0,101107,Marvin Williams,1.610613e+09,Charlotte,Hornets,CHA,5,201587,Nicolas Batum,1.610613e+09,Charlotte,Hornets,CHA,0,0,NaN,NaN,NaN,NaN,NaN,80.28932,16.94484,3.53788,1.610613e+09,2449.0,85.23450,20.38978,1.610613e+09,201960.0,63.62820,33.09987,1.610613e+09,200768.0,86.69220,29.65742,1.610613e+09,201942.0,84.84322,1.52255,1.610613e+09,202685.0,79.48484,24.93224,1.610613e+09,101107.0,79.45158,17.14905,1.610613e+09,201587.0,79.96933,4.10200,1.610613e+09,202689.0,70.65765,21.60912,1.610613e+09,203087.0,83.31356,37.29335,1.610613e+09,1626163.0,50.41203,23.14616,79.45158,17.14905,5.78292,3.24073,6.629064,0.03326,7.78319,7.783261,7.24062,12.50837,14.452885,5.39164,-15.62650,16.530496,-15.82338,15.95082,22.467933,-8.79393,4.46007,9.860296,0.51775,-13.04705,13.057319,3.86198,20.14430,20.511161,-29.03955,5.99711,29.652332,79.45158,17.14905,5.78292,3.24073,6.629064,0.03326,7.78319,7.783261,7.24062,12.50837,14.452885,5.39164,-15.62650,16.530496,-15.82338,15.95082,22.467933,-8.79393,4.46007,9.860296,0.51775,-13.04705,13.057319,3.86198,20.14430,20.511161,-29.03955,5.99711,29.652332,79.45158,17.14905,5.78292,3.24073,6.629064,0.03326,7.78319,7.783261,7.24062,12.50837,14.452885,5.39164,-15.62650,16.530496,-15.82338,15.95082,22.467933,-8.79393,4.46007,9.860296,0.51775,-13.04705,13.057319,3.86198,20.14430,20.511161,-29.03955,5.99711,29.652332,79.45158,17.14905,5.78292,3.24073,6.629064,0.03326,7.78319,7.783261,7.24062,12.50837,14.452885,5.39164,-15.62650,16.530496,-15.82338,15.95082,22.467933,-8.79393,4.46007,9.860296,0.51775,-13.04705,13.057319,3.86198,20.14430,20.511161,-29.03955,5.99711,29.652332,79.45158,17.14905,5.78292,3.24073,6.629064,0.03326,7.78319,7.783261,7.24062,12.50837,14.452885,5.39164,-15.62650,16.530496,-15.82338,15.95082,22.467933,-8.79393,4.46007,9.860296,0.51775,-13.04705,13.057319,3.86198,20.14430,20.511161,-29.03955,5.99711,29.652332,79.45158,17.14905,5.78292,3.24073,6.629064,0.03326,7.78319,7.783261,7.24062,12.50837,14.452885,5.39164,-15.62650,16.530496,-15.82338,15.95082,22.467933,-8.79393,4.46007,9.860296,0.51775,-13.04705,13.057319,3.86198,20.14430,20.511161,-29.03955,5.99711,29.652332,5.784319

In [5]:
df.info(max_cols=200, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 84466 entries, 0 to 84465
Columns: 296 entries, shooter_slot to shooter_speed
dtypes: float64(245), int64(22), str(29)
memory usage: 208.4 MB

In [6]:
df = df.dropna(subset=['shooter_x', 'shooter_y', 'shooter_speed', 'defender_closing_speed'])
#df = df.dropna(subset=['shooter_x', 'shooter_y', 'defender_closing_speed'])

In [7]:
df.info(max_cols=200, show_counts=True)

<class 'pandas.DataFrame'>
Index: 84124 entries, 0 to 84465
Columns: 296 entries, shooter_slot to shooter_speed
dtypes: float64(245), int64(22), str(29)
memory usage: 208.4 MB

In [8]:
if do_filter_for_players:
    df = filter_for_players(df)
    df.info(max_cols=200, show_counts=True)

<class 'pandas.DataFrame'>
Index: 8151 entries, 206 to 84245
Columns: 296 entries, shooter_slot to shooter_speed
dtypes: float64(245), int64(22), str(29)
memory usage: 20.2 MB

In [9]:
df['PLAYER_NAME'].unique()

<ArrowStringArray>
[        'Dirk Nowitzki',           'Dwyane Wade',             'Pau Gasol',
         'Stephen Curry',        'Draymond Green',         'Manu Ginobili',
          'James Harden',            'Tim Duncan',           'Tony Parker',
         'Kawhi Leonard', 'Giannis Antetokounmpo',         'Kevin Garnett',
         'Anthony Davis',          'Kevin Durant',     'Russell Westbrook',
          'LeBron James',            'Chris Paul',           'Kobe Bryant',
          'Nikola Jokic']
Length: 19, dtype: str

# Generate additional features

In [10]:
# 1. Extract player data
p_x = df[[f"player{i}_x" for i in range(1, 11)]].to_numpy()
p_y = df[[f"player{i}_y" for i in range(1, 11)]].to_numpy()
p_ids = df[[f"player{i}_id" for i in range(1, 11)]].to_numpy()
p_teams = df[[f"player{i}_team_id" for i in range(1, 11)]].to_numpy()

# shooter data
s_x = df["shooter_x"].to_numpy()[:, np.newaxis]
s_y = df["shooter_y"].to_numpy()[:, np.newaxis]
s_id = df["PLAYER_ID"].to_numpy()[:, np.newaxis]
s_team = df["TEAM_ID"].to_numpy()[:, np.newaxis]

# helper: distance between shooter and all players
dx = p_x - s_x
dy = p_y - s_y
dist_to_players = np.sqrt(dx**2 + dy**2)

## Helpers

In [11]:
def get_nearest_teammate_dist(dist_to_players, p_teams, s_team, p_ids, s_id):
    mask = (p_teams == s_team) & (p_ids != s_id)
    masked_dist = np.where(mask, dist_to_players, np.inf)
    min_dist = np.min(masked_dist, axis=1)
    return np.where(min_dist == np.inf, np.nan, min_dist)

def get_defenders_between_shooter_and_basket(p_x, p_y, s_x, s_y, p_teams, s_team, bx, by):
    '''Check if there is a defender between the shooter and the basket'''
    
    # Vector Shooter -> Basket
    vec_b_x, vec_b_y = bx - s_x, by - s_y
    norm_b_sq = vec_b_x**2 + vec_b_y**2
    
    # Vector Shooter -> all players
    vec_p_x, vec_p_y = p_x - s_x, p_y - s_y
    
    # projection and distance
    dot = vec_p_x * vec_b_x + vec_p_y * vec_b_y
    proj_rel = dot / norm_b_sq
    
    perp_dist = np.sqrt((vec_p_x - proj_rel * vec_b_x)**2 + (vec_p_y - proj_rel * vec_b_y)**2)
    
    # filter: enemy player, between shoter and basket and close to connection line
    mask = (p_teams != s_team) & (proj_rel > 0) & (proj_rel < 1) & (perp_dist < 3)
    return np.sum(mask, axis=1)

def get_detect_screen(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players):
    '''Check if there is a screening player between the shooter and the basket'''
    
    # get closest defender
    def_mask = (p_teams != s_team)
    masked_def_dist = np.where(def_mask, dist_to_players, np.inf)
    nearest_def_idx = np.argmin(masked_def_dist, axis=1)
    
    # coords of closest defendet
    rows = np.arange(len(p_x))
    dx_near, dy_near = p_x[rows, nearest_def_idx][:, np.newaxis], p_y[rows, nearest_def_idx][:, np.newaxis]
    
    # 2. vector shooter -> nearest defender
    line_x, line_y = dx_near - s_x, dy_near - s_y
    line_norm_sq = line_x**2 + line_y**2
    line_norm_sq[line_norm_sq == 0] = 1e-9
    
    # check teammates
    vec_p_x, vec_p_y = p_x - s_x, p_y - s_y
    dot = vec_p_x * line_x + vec_p_y * line_y
    proj_rel = dot / line_norm_sq
    
    perp_dist = np.sqrt((vec_p_x - proj_rel * line_x)**2 + (vec_p_y - proj_rel * line_y)**2)
    dist_to_def = np.sqrt((p_x - dx_near)**2 + (p_y - dy_near)**2)
    
    # screen criteria: teammate between shooter and defender and not too for to the defender
    tm_mask = (p_teams == s_team) & (p_ids != s_id)
    is_between = (proj_rel > 0) & (proj_rel < 1)
    screen_found = tm_mask & is_between & (perp_dist < 2) & (dist_to_def < 5)
    
    return np.any(screen_found, axis=1).astype(int)

def get_offensive_spacing(p_x, p_y, p_teams, s_team):
    '''Compute offensive spacing as mean distances between all offensive players'''
    
    spacing = []
    for i in range(len(p_x)):
        # filter for offensive players
        off_mask = (p_teams[i] == s_team[i])
        off_coords = np.stack([p_x[i, off_mask], p_y[i, off_mask]], axis=1)
        
        if len(off_coords) < 2:
            spacing.append(np.nan)
            continue
            
        # distances for all combinations
        dists = []
        for p1, p2 in combinations(off_coords, 2):
            dists.append(np.linalg.norm(p1 - p2))
        spacing.append(np.mean(dists))
        
    return np.array(spacing)

def get_teammate_between_defender(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players):
    '''
        Check if there is a teammate between the shooter and the next defending player.
        Similar to get screening player, but without min distance to defender
    '''
    
    def_mask = (p_teams != s_team)
    masked_def_dist = np.where(def_mask, dist_to_players, np.inf)
    nearest_def_idx = np.argmin(masked_def_dist, axis=1)
    
    rows = np.arange(len(p_x))
    dx_near, dy_near = p_x[rows, nearest_def_idx][:, np.newaxis], p_y[rows, nearest_def_idx][:, np.newaxis]
    
    line_x, line_y = dx_near - s_x, dy_near - s_y
    line_norm_sq = line_x**2 + line_y**2
    line_norm_sq[line_norm_sq == 0] = 1e-9
    
    vec_p_x, vec_p_y = p_x - s_x, p_y - s_y
    proj_rel = (vec_p_x * line_x + vec_p_y * line_y) / line_norm_sq
    perp_dist = np.sqrt((vec_p_x - proj_rel * line_x)**2 + (vec_p_y - proj_rel * line_y)**2)
    
    tm_mask = (p_teams == s_team) & (p_ids != s_id)
    between = tm_mask & (proj_rel > 0) & (proj_rel < 1) & (perp_dist < 5)
    
    return np.any(between, axis=1).astype(int)

def get_players_in_paint(p_x, p_y):
    '''Get the amount of players in the paint'''
    in_paint = (p_x > 94-19) & (p_x <= 94) & (p_y > 17) & (p_y < 33)
    return np.sum(in_paint, axis=1)

In [12]:
df["nearest_teammate_distance"] = get_nearest_teammate_dist(dist_to_players, p_teams, s_team, p_ids, s_id)
df["defenders_between"] = get_defenders_between_shooter_and_basket(p_x, p_y, s_x, s_y, p_teams, s_team, basket_x, basket_y)
df["has_screen"] = get_detect_screen(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players)
df["offensive_spacing"] = get_offensive_spacing(p_x, p_y, p_teams, s_team)
df["teammate_between_defender"] = get_teammate_between_defender(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players)
df["players_in_paint"] = get_players_in_paint(p_x, p_y)

C:\Users\jonas\AppData\Local\Temp\ipykernel_14492\3528505643.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["nearest_teammate_distance"] = get_nearest_teammate_dist(dist_to_players, p_teams, s_team, p_ids, s_id)
C:\Users\jonas\AppData\Local\Temp\ipykernel_14492\3528505643.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["defenders_between"] = get_defenders_between_shooter_and_basket(p_x, p_y, s_x, s_y, p_teams, s_team, basket_x, basket_y)
C:\Users\jonas\AppData\Local\Temp\ipykernel_14492\3528505643.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["has_screen"] = get_detect_screen(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players)
C:\Users\jonas\AppData\Local\Temp\ipykernel_14492\3528505643.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["offensive_spacing"] = get_offensive_spacing(p_x, p_y, p_teams, s_team)
C:\Users\jonas\AppData\Local\Temp\ipykernel_14492\3528505643.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["teammate_between_defender"] = get_teammate_between_defender(p_x, p_y, s_x, s_y, p_teams, s_team, p_ids, s_id, dist_to_players)
C:\Users\jonas\AppData\Local\Temp\ipykernel_14492\3528505643.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["players_in_paint"] = get_players_in_paint(p_x, p_y)

# Check und export

In [13]:
df.head()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,ball_height,defender_closing_speed,ball_speed,ball_xy_speed,ACTION_TYPE,EVENTTIME,EVENT_TYPE,GAME_DATE,GAME_EVENT_ID,GAME_ID,GRID_TYPE,HTM,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,PLAYER_NAME,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,SHOT_TYPE,SHOT_ZONE_AREA,SHOT_ZONE_BASIC,SHOT_ZONE_RANGE,TEAM_ID,TEAM_NAME,VTM,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_WCTIMESTRING,event_PCTIMESTRING,event_HOMEDESCRIPTION,event_NEUTRALDESCRIPTION,event_VISITORDESCRIPTION,event_SCORE,event_SCOREMARGIN,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_NAME,event_PLAYER1_TEAM_ID,event_PLAYER1_TEAM_CITY,event_PLAYER1_TEAM_NICKNAME,event_PLAYER1_TEAM_ABBREVIATION,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_NAME,event_PLAYER2_TEAM_ID,event_PLAYER2_TEAM_CITY,event_PLAYER2_TEAM_NICKNAME,event_PLAYER2_TEAM_ABBREVIATION,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_NAME,event_PLAYER3_TEAM_ID,event_PLAYER3_TEAM_CITY,event_PLAYER3_TEAM_NICKNAME,event_PLAYER3_TEAM_ABBREVIATION,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5,shooter_speed,nearest_teammate_distance,defenders_between,has_screen,offensive_spacing,teammate_between_defender,players_in_paint
206,6.0,68.07977,11.40150,1.610613e+09,32.714283,25.161436,3.129454,19.151729,0.0,1.0,1.0,897.519148,10.09470,1.753045,18.868386,17.889591,Jump Shot,607,Missed Shot,20160101,11,21500491,Shot Chart Detail,MIA,-126.7654,207.7669,10,1,1717,Dirk Nowitzki,1.0,7,1,25,0,609.83,3PT Field Goal,Left Side Center(LC),Above the Break 3,24+ ft.,1610612742,Dallas Mavericks,DAL,609.83,609.83,21500491,11,2,1,1,7:44 PM,10:07,NaN,NaN,MISS Nowitzki 25' 3PT Jump Shot,NaN,NaN,5.0,1717,Dirk Nowitzki,1.610613e+09,Dallas,Mavericks,DAL,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,68.47331,12.32346,10.09470,1.610613e+09,2547.0,65.95351,26.18923,1.610613e+09,2736.0,70.24542,13.66058,1.610613e+09,201609.0,76.51012,36.81507,1.610613e+09,202355.0,81.97215,22.66092,1.610613e+09,204020.0,85.72836,39.32333,1.610613e+09,1717.0,68.07977,11.40150,1.610613e+09,200826.0,52.72887,28.18870,1.610613e+09,2585.0,88.19651,13.73115,1.610613e+09,202083.0,74.25066,46.11072,1.610613e+09,202718.0,87.98636,48.26277,68.07977,11.40150,2.16565,2.25908,3.129454,-2.12626,14.78773,14.939811,13.89238,11.25942,17.882191,8.43035,25.41357,26.775368,17.64859,27.92183,33.031823,20.11674,2.32965,20.251185,-15.35090,16.78720,22.747752,6.17089,34.70922,35.253508,19.90659,36.86127,41.893025,68.07977,11.40150,2.16565,2.25908,3.129454,-2.12626,14.78773,14.939811,13.89238,11.25942,17.882191,8.43035,25.41357,26.775368,17.64859,27.92183,33.031823,20.11674,2.32965,20.251185,-15.35090,16.78720,22.747752,6.17089,34.70922,35.253508,19.90659,36.86127,41.893025,68.07977,11.40150,2.16565,2.25908,3.129454,-2.12626,14.78773,14.939811,13.89238,11.25942,17.882191,8.43035,25.41357,26.775368,17.64859,27.92183,33.031823,20.11674,2.32965,20.251185,-15.35090,16.78720,22.747752,6.17089,34.70922,35.253508,19.90659,36.86127,41.893025,68.07977,11.40150,2.16565,2.25908,3.129454,-2.12626,14.78773,14.939811,13.89238,11.25942,17.882191,8.43035,25.41357,26.775368,17.64859,27.92183,33.031823,20.11674,2.32965,20.251185,-15.35090,16.78720,22.747752,6.17089,34.70922,35.253508,19.90659,36.86127,41.893025,68.07977,11.40150,2.16565,2.25908,3.129454,-2.12626,14.78773,14.939811,13.89238,11.25942,17.882191,8.43035,25.41357,26.775368,17.64859,27.92183,33.031823,20.11674,2.32965,20.251185,-15.35090,16.78720,22.747752,6.17089,34.70922,35.253508,19.90659,36.86127,41.893025,68.07977,11.40150,2.16565,2.25908,3.129454,-2.12626,14.78773,14.939811,13.89238,11.25942,17.882191,8.43035,25.41357,26.775368,17.64859,27.92183,33.031823,20.11674,2.32965,20.251185,-15.35090,16.78720,22.747752,6.17089,34.70922,35.253508,19.90659,36.86127,41.893025,3.476063,20.251185,2,0,31.071576,0,1
207,6.0,89.28413,37.53776,1.610613e+09,-90.155969,12.537806,3.383296,14.730753,0.0,1.0,1.0,595.443969,6.25343,-1.084407,9.820973,5.726668,Jump Shot,547,Missed Shot,20160101,21,21500491,Shot Chart Detail,MIA,117.2049,-6.8476,9,1,1717,Dirk Nowitzki,1.0,7,1,15,0,549.01,2PT Field Goal,Right Side(R),Mid-Range,8-16 ft.,1610612742,Dallas Mavericks,DAL,549.01,549.01,21500491,21,2,1,1,7:45 PM,9:07,NaN,NaN,MISS Nowitzki 16' Jump Shot,NaN,NaN,5.0,1717,Dirk Nowitzki,1.610613e+09,Dallas,Mavericks,DAL,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,89.93476,36.72049,6.25343,1.610613e+09,2547.0,87.06863,34.98076,1.610613e+09,2736.0,80.04136,40.03633,1.610613e+09,201609.0,74.63384,19.60262,1.610613e+09,202355.0,83.73609,19.18209,1.610613e+09,204020.0,73.12533,28.81678,1.610613e+09,1717.0,89.28413,37.53776,1.610613e+09,200826.0,62.09240,11.67649,1.610613e+09,2585.0,80.30646,13.82874,1.610613e+09,202083.0,62.21486,27.11115,1.610613e+09,202718.0,72.00673,44.25016,89.28413,37.53776,-2.21550,-2.55700,3.383296,-9.24277,2.49857,9.574531,-16.15880,-8.72098,18.361980,-5.54804,-18.35567,19.175802,-14.65029,-17.93514,23.158157,-17.27740,6.71240,18.535503,-8.97767,-23.70902,25.351848,-27.06927,-10.42661,29.007923,-27.19173,-25.86127,37.525931,89.28413,37.53776,-2.21550,-2.55700,3.383296,-9.24277,2.49857,9.574531,-16.15880,-8.72098,18.361980,-5.54804,-18.35567,19.175802,-14.65029,-17.93514,23.158157,-17.27740,6.71240,18.535503,-8.97767,-23.70902,25.351848,-27.06927,-10.42661,29.007923,-27.19173,-25.86127,37.525931,89.28413,37.53776,-2.21550,-2.55700,3.383296,-9.24277,2.49857,9.574531,-16.15880,-8.72098,18.361980,-5.54804,-18.35567,19.175802,-14.65029,-17.93514,23.158157,-17.27740,6.71240,18.535503,-8.97767,-23.70902,25.351848,-27.06927,-10.42661,29.007923,-27.19173,-25.86127,37.525931,89.28413,37.53776,-2.21550,-2.55700,3.383296,-9.24277,2.49857,9.574531,-16.15880,-8.72098,18.361980,-5.54804,-18.35567,19.175802,-14.65029,-17.93514,23.158157,-17.27740,6.71240,18.535503,-8.97767,-23.70902,25.351848,-27.06927,-10.42661,29.007923,-27.19173,-25.86127,37.525931,89.28413,37.53776,-2.21550,-2.55700,3.383296,-9.24277,2.49857,9.574531,-16.15880,-8.72098,18.361980,-5.54804,-18.35567,19.175802,-14.65029,-17.93514,23.158157,-17.27740,6.71240,18.535503,-8.97767,-23.70902,25.351848,-27.06927,-10.42661,29.007923,-27.19173,-25.86127,37.525931,89.28413,37.53776,-2.21550,-2.55700,3.383296,-9.24277,2.49857,9.574531,-16.15880,-8.72098,18.361980,-5.54804,-18.35567,19.175802,-14.65029,-17.93514,23.158157,-17.27740,6.71240,18.535503,-8.97767,-23.70902,25.351848,-27.06927,-10.42661,29.007923,-27.19173,-25.86127,37.525931,4.136060,18.535503,1,0,25.196232,0,1
208,6.0,71.74908,33.31741,1.610613e+09,-25.419665,19.376829,4.907785,17.035144,0.0,1.0,1.0,174.666105,8.52746,-1.491129,19.371197,18.096994,Jump Shot,434,Missed Shot,20160101,38,21500491,Shot Chart Detail,MIA,101.7517,214.8868,7,1,1717,Dirk Nowitzki,1.0,14,1,14,0,419.14,2PT Field Goal,Left Side(L),Mid-Range,8-16 ft.,1610612742,Dallas Mavericks,DAL,419.14,419.14,21500491,38,2,1,1,7:48 PM,7:14,NaN,NaN,MISS Nowitzki 15' Jump Shot,NaN,NaN,5.0,1717,Dirk Nowitzki,1.610613e+09,Dallas,Mavericks,DAL,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,67.76132,35.17517,8.52746,1.610613e+09,2547.0,67.11049,34.92048,1.610613e+09,2736.0,88.43522,48.26660,1.610613e+09,201609.0,85.62424,1.79544,1.610613e+09,202355.0,75.41067,23.71748,1.610613e+09,204020.0,79.75736,43.74710,1.610613e+09,1717.0,71.74908,33.31741,1.610613e+09,200826.0,79.95826,38.36333,1.610613e+09,2585.0,78.55788,25.67070,1.610613e+09,202083.0,83.53046,13.92467,1.610613e+09,202718.0,85.37829,37.86715,71.74908,33.31741,-4.63859,1.60307,4.907785,3.66159,-9.59993,10.274527,8.00828,10.42969,13.149562,16.68614,14.94919,22.403249,13.87516,-31.52197,34.440596,8.20918,5.04592,9.635971,6.80880,-7.64671,10.238747,13.62921,4.54974,14.368559,11.78138,-19.39274,22.690951,71.74908,33.31741,-4.63859,1.60307,4.907785,3.66159,-9.59993,10.274527,8.00828,10.42969,13.149562,16.68614,14.94919,22.403249,13.87516,-31.52197,34.440596,8.20918,5.04592,9.635971,6.80880,-7.64671,10.238747,13.62921,4.54974,14.368559,11.78138,-19.39274,22.690951,71.74908,33.31741,-4.63859,1.60307,4.907785,3.66159,-9.59993,10.274527,8.00828,10.42969,13.149562,16.68614,14.94919,22.403249,13.87516,-31.52197,34.440596,8.20918,5.04592,9.635971,6.80880,-7.64671,10.238747,13.62921,4.54974,14.368559,11.78138,-19.39274,22.690951,71.74908,33.31741,-4.63859,1.60307,4.907785,3.66159,-9.59993,10.274527,8.00828,10.42969,13.149562,16.68614,14.94919,22.403249,13.87516,-31.52197,34.440596,8.20918,5.04592,9.635971,6.80880,-7.64671,10.238747,13.62921,4.54974,14.368559,11.78138,-19.39274,22.690951,71.74908,33.31741,-4.63859,1.60307,4.907785,3.66159,-9.59993,10.274527,8.00828,10.42969,13.149562,16.68614,14.94919,22.403249,13.87516,-31.52197,34.440596,8.20918,5.04592,9.635971,6.80880,-7.64671,10.238747,13.62921,4.54974,14.368559,11.78138,-19.39274,22.690951,71.74908,33.31741,-4.63859,1.60307,4.907785,3.66159,-9.59993,10.274527,8.00828,10.42969,13.149562,16.68614,14.94919,22.403249,13.87516,-31.52197,34.440596,8.20918,5.04592,9.635971,6.80880,-7.64671,10.238747,13.62921,4.54974,14.368559,11.78138,-19.39274,22.690951,8.090446,9.635971,0,0,15.058779,0,2
209,6.0,88.37780,41.25803,1.610613e+09,-86.929178,16.281409,3.011054,14.145881,0.0,1.0,1.0,401.614640,8.26425,3.590027,14.212587,13.505246,Jump Shot,113,Missed Shot,20160101,93,21500491,Shot Chart Detail,MIA,153.4937,7.9205,1,1,1717,Dirk Nowitzki,1.0,53,1,19,0,115.89,2PT Field Goal,Right Side(R),Mid-Range,16-24 ft.,1610612742,Dallas Mavericks,DAL,115.89,115.89,21500491,93,2,1,1,8:00 PM,1:53,NaN,NaN,MISS Nowitzki 19' Jump Shot,NaN,NaN,5.0,1717,Dirk Nowitzki,1.610613e+09,Dallas,Mavericks,DAL,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,88.45795,40.34937,8.26425,1.610613e+09,2547.0,90.83952,33.00610,1.610613e+09,2757.0,76.65048,37.80458,1.610613e+09,101123.0,83.89017,14.28075,1.610613e+09,201609.0,86.32245,39.05758,1.610613e+09,202355.0,78.88278,24.18714,1.610613e+09,1717.0,88.37780,41.25803,1.610613e+09,2734.0,87.50655,25.37443,1.610613e+09,200826.0,71.34816,43.60872,1.610613e+09,202718.0,77.68002,3.62044,1.610613e+09,203939.0,74.44340,24.71692,88.37780,41.25803,-2.05535,-2.20045,3.011054,2.46172,-8.25193,8.611296,-11.72732,-3.45345,12.225234,-9.49502,-17.07089,19.533834,-4.48763,-26.97728,27.347988,-0.87125,-15.88360,15.907477,-17.02964,2.35069,17.191113,-13.93440,-16.54111,21.628126,-10.69778,-37.63759,39.128387,88.37780,41.25803,-2.05535,-2.20045,3.011054,2.46172,-8.25193,8.611296,-11.72732,-3.45345,12.225234,-9.49502,-17.07089,19.533834,-4.48763,-26.97728,27.347988,-0.87125,-15.88360,15.907477,-17.02964,2.35069,17.191113,-13.93440,-16.54111,21.628126,-10.69778,-37.63759,39.128387,88.37780,41.25803,-2.05535,-2.20045,3.011054,2.46172,-8.25193,8.611296,-11.72732,-3.45345,12.225234,-9.49502,-17.07089,19.533834,-4.48763,-26.97728,27.347988,-0.87125,-15.88360,15.907477,-17.02964,2.35069,17.191113,-13.93440,-16.54111,21.628126,-10.69778,-37.63759,39.128387,88.37780,41.25803,-2.05535,-2.20045,3.011054,2.46172,-8.25193,8.611296,-11.72732,-3.45345,12.225234,-9.49502,-17.07089,19.533834,-4.48763,-26.97728,27.347988,-0.87125,-15.88360,15.907477,-17.02964,2.35069,17.191113,-13.93440,-16.54111,21.628126,-10.69778,-37.63759,39.128387,88.37780,41.25803,-2.05535,-2.20045,3.011054,2.46172,-8.25193,8.611296,-11.72732,-3.45345,12.225234,-9.49502,-17.07089,19.533834,-4.48763,-26.97728,27.347988,-0.87125,-15.88360,15.907477,-17.02964,2.35069,17.191113,-13.93440,-16.54111,21.628126,-10.69778,-37.63759,39.128387,88.37780,41.25803,-2.05535,-2.20045,3.011054,2.46172,-8.25193,8.611296,-11.72732,-3.45345,12.225234,-9.49502,-17.07089,19.533834,-4.48763,-26.97728,27.347988,-0.87125,-15.88360,15.907477,-17.02964,2.35069,17.191113,-13.93440,-16.54111,21.628126,-10.69778,-37.63759,39.128387,4.309460,15.907477,2,0,23.614224,0,2
210,6.0,70.51797,34.83885,1.610613e+09,-27.710344,21.158731,4.035961,16.071842,0.0,1.0,1.0,565.902648,8.78230,0.163115,21.238528,20.369714,Jump Shot,56,Made Shot,20160101,99,21500491,Shot Chart Detail,MIA,-54.9521,261.4170,0,1,1717,Dirk Nowitzki,1.0,56,1,17,1,71.78,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,1610612742,Dallas Mavericks,DAL,71.78,71.78,21500491,99,1,1,1,8:01 PM,0:56,NaN,NaN,Nowitzki 17' Jump Shot (2 PTS),10 - 20,10,5.0,1717,Dirk Nowitzki,1.610613e+09,Dallas,Mavericks,DAL,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,63.10830,19.50479,8.78230,1.610613e+09,2547.0,67.45198,21.33838,1.610613e+09,2757.0,61.47932,14.94017,1.610613e+09,101123.0,73.75553,32.42904,1.610613e+09,201609.0,84.60756,15.41773,1.610613e+09,202355.0,84.97860,26.62619,1.610613e+09,1717.0,70.51797,34.83885,1.610613e+09,2734.0,88.04106,1.18215,1.610613e+09,200826.0,54.18526,18.10867,1.610613e+09,202718.0,63.04277,19.18817,1.610613e+09,203939.0,88.96235,15.90148,70.51797,34.83885,3.23756,-2.40981,4.035961,-3.06599,-13.50047,13.844240,14.46063,-8.21266,16.630021,-9.03865,-19.89868,21.855312,14.08959,-19.42112,23.993675,-7.47520,-15.65068,17.344232,-16.33271,-16.73018,23.380683,18.44438,-18.93737,26.435187,17.52309,-33.65670,37.945120,70.51797,34.83885,3.23756,-2.40981,4.035961,-3.06599,-13.50047,13.844240,14.46063,-8.21266,16.630021,-9.03865,-19.89868,21.855312,14.08959,-19.42112,23.993675,-7.47520,-15.65068,17.344232,-16.33271,-16.73018,23.380683,18.44438,-18.93737,26.435187,17.52309,-33.65670,37.945120,70.51797,34.83885,3.23756,-2.40981,4.035961,-3.06599,-13.50047,13.844240,14.46063,-8.21266,16.630021,-9.03865,-19.89868,21.855312,14.08959,-19.42112,23.993675,-7.47520,-15.65068,17.344232,-16.33271,-16.73018,23.380683,18.44438,-18.93737,26.435187,17.52309,-33.65670,37.945120,70.51797,34.83885,3.23756,-2.40981,4.035961,-3.06599,-13.50047,13.844240,14.46063,-8.21266,16.630021,-9.03865,-19.89868,21.855312,14.08959,-19.42112,23.993675,-7.47520,-15.65068,17.344232,-16.33271,-16.73018,23.380683,18.44438,-18.93737,26.435187,17.52309,-33.65670,37.945120,70.51797,34.83885,3.23756,-2.40981,4.035961,-3.06599,-13.50047,13.844240,14.46063,-8.21266,16.630021,-9.03865,-19.89868,21.855312,14.08959,-19.42112,23.993675,-7.47520,-15.65068,17.344232,-16.33271,-16.73018,23.380683,18.44438,-18.93737,26.435187,17.52309,-33.65670,37.945120,70.51797,34.83885,3.23756,-2.40981,4.035961,-3.06599,-13.50047,13.844240,14.46063,-8.21266,16.630021,-9.03865,-19.89868,21.855312,14.08959,-19.42112,23.993675,-7.47520,-15.65068,17.344232,-16.33271,-16.73018,23.380683,18.44438,-18.93737,26.435187,17.52309,-33.65670,37.945120,4.186018,17.344232,2,0,25.840989,0,1

In [14]:
df.info(max_cols=350, show_counts=True)

<class 'pandas.DataFrame'>
Index: 8151 entries, 206 to 84245
Data columns (total 302 columns):
 #    Column                           Non-Null Count  Dtype
---   ------                           --------------  -----
 0    shooter_slot                     8151 non-null   float64
 1    shooter_x                        8151 non-null   float64
 2    shooter_y                        8151 non-null   float64
 3    shooter_team_id                  8151 non-null   float64
 4    shot_angle                       8151 non-null   float64
 5    distance_to_basket_tracking      8151 non-null   float64
 6    nearest_defender_dist            8151 non-null   float64
 7    avg_defender_dist                8151 non-null   float64
 8    defenders_within_3ft             8151 non-null   float64
 9    defenders_within_5ft             8151 non-null   float64
 10   defenders_within_7ft             8151 non-null   float64
 11   offensive_spacing_area           8151 non-null   float64
 12   ball_height                      8151 non-null   float64
 13   defender_closing_speed           8151 non-null   float64
 14   ball_speed                       8151 non-null   float64
 15   ball_xy_speed                    8151 non-null   float64
 16   ACTION_TYPE                      8151 non-null   str
 17   EVENTTIME                        8151 non-null   int64
 18   EVENT_TYPE                       8151 non-null   str
 19   GAME_DATE                        8151 non-null   int64
 20   GAME_EVENT_ID                    8151 non-null   int64
 21   GAME_ID                          8151 non-null   int64
 22   GRID_TYPE                        8151 non-null   str
 23   HTM                              8151 non-null   str
 24   LOC_X                            8151 non-null   float64
 25   LOC_Y                            8151 non-null   float64
 26   MINUTES_REMAINING                8151 non-null   int64
 27   PERIOD                           8151 non-null   int64
 28   PLAYER_ID                        8151 non-null   int64
 29   PLAYER_NAME                      8151 non-null   str
 30   QUARTER                          8151 non-null   float64
 31   SECONDS_REMAINING                8151 non-null   int64
 32   SHOT_ATTEMPTED_FLAG              8151 non-null   int64
 33   SHOT_DISTANCE                    8151 non-null   int64
 34   SHOT_MADE_FLAG                   8151 non-null   int64
 35   SHOT_TIME                        8151 non-null   float64
 36   SHOT_TYPE                        8151 non-null   str
 37   SHOT_ZONE_AREA                   8151 non-null   str
 38   SHOT_ZONE_BASIC                  8151 non-null   str
 39   SHOT_ZONE_RANGE                  8151 non-null   str
 40   TEAM_ID                          8151 non-null   int64
 41   TEAM_NAME                        8151 non-null   str
 42   VTM                              8151 non-null   str
 43   tracking_game_clock              8151 non-null   float64
 44   tracking_game_clock_old          8151 non-null   float64
 45   event_GAME_ID                    8151 non-null   int64
 46   event_EVENTNUM                   8151 non-null   int64
 47   event_EVENTMSGTYPE               8151 non-null   int64
 48   event_EVENTMSGACTIONTYPE         8151 non-null   int64
 49   event_PERIOD                     8151 non-null   int64
 50   event_WCTIMESTRING               8151 non-null   str
 51   event_PCTIMESTRING               8151 non-null   str
 52   event_HOMEDESCRIPTION            4390 non-null   str
 53   event_NEUTRALDESCRIPTION         0 non-null      float64
 54   event_VISITORDESCRIPTION         4115 non-null   str
 55   event_SCORE                      3839 non-null   str
 56   event_SCOREMARGIN                3839 non-null   str
 57   event_PERSON1TYPE                8151 non-null   float64
 58   event_PLAYER1_ID                 8151 non-null   int64
 59   event_PLAYER1_NAME               8151 non-null   str
 60   event_PLAYER1_TEAM_ID            8151 non-null   float64
 61   event_PLAYER1_TEAM_CITY          8151 non-null   str
 62   event_PLAYER1_TEAM_NICKNAME      8151 non-null   str
 63   event_PLAYER1_TEAM_ABBREVIATION  8151 non-null   str
 64   event_PERSON2TYPE                8151 non-null   int64
 65   event_PLAYER2_ID                 8151 non-null   int64
 66   event_PLAYER2_NAME               1897 non-null   str
 67   event_PLAYER2_TEAM_ID            1897 non-null   float64
 68   event_PLAYER2_TEAM_CITY          1897 non-null   str
 69   event_PLAYER2_TEAM_NICKNAME      1897 non-null   str
 70   event_PLAYER2_TEAM_ABBREVIATION  1897 non-null   str
 71   event_PERSON3TYPE                8151 non-null   int64
 72   event_PLAYER3_ID                 8151 non-null   int64
 73   event_PLAYER3_NAME               354 non-null    str
 74   event_PLAYER3_TEAM_ID            354 non-null    float64
 75   event_PLAYER3_TEAM_CITY          354 non-null    str
 76   event_PLAYER3_TEAM_NICKNAME      354 non-null    str
 77   event_PLAYER3_TEAM_ABBREVIATION  354 non-null    str
 78   ball_x                           8151 non-null   float64
 79   ball_y                           8151 non-null   float64
 80   ball_z                           8151 non-null   float64
 81   player1_team_id                  8151 non-null   float64
 82   player1_id                       8151 non-null   float64
 83   player1_x                        8151 non-null   float64
 84   player1_y                        8151 non-null   float64
 85   player2_team_id                  8151 non-null   float64
 86   player2_id                       8151 non-null   float64
 87   player2_x                        8151 non-null   float64
 88   player2_y                        8151 non-null   float64
 89   player3_team_id                  8151 non-null   float64
 90   player3_id                       8151 non-null   float64
 91   player3_x                        8151 non-null   float64
 92   player3_y                        8151 non-null   float64
 93   player4_team_id                  8151 non-null   float64
 94   player4_id                       8151 non-null   float64
 95   player4_x                        8151 non-null   float64
 96   player4_y                        8151 non-null   float64
 97   player5_team_id                  8151 non-null   float64
 98   player5_id                       8151 non-null   float64
 99   player5_x                        8151 non-null   float64
 100  player5_y                        8151 non-null   float64
 101  player6_team_id                  8151 non-null   float64
 102  player6_id                       8151 non-null   float64
 103  player6_x                        8151 non-null   float64
 104  player6_y                        8151 non-null   float64
 105  player7_team_id                  8151 non-null   float64
 106  player7_id                       8151 non-null   float64
 107  player7_x                        8151 non-null   float64
 108  player7_y                        8151 non-null   float64
 109  player8_team_id                  8151 non-null   float64
 110  player8_id                       8151 non-null   float64
 111  player8_x                        8151 non-null   float64
 112  player8_y                        8151 non-null   float64
 113  player9_team_id                  8151 non-null   float64
 114  player9_id                       8151 non-null   float64
 115  player9_x                        8151 non-null   float64
 116  player9_y                        8151 non-null   float64
 117  player10_team_id                 8151 non-null   float64
 118  player10_id                      8151 non-null   float64
 119  player10_x                       8151 non-null   float64
 120  player10_y                       8151 non-null   float64
 121  shooter_x_t0                     8151 non-null   float64
 122  shooter_y_t0                     8151 non-null   float64
 123  defender1_dx_t0                  8151 non-null   float64
 124  defender1_dy_t0                  8151 non-null   float64
 125  defender1_dist_t0                8151 non-null   float64
 126  defender2_dx_t0                  8151 non-null   float64
 127  defender2_dy_t0                  8151 non-null   float64
 128  defender2_dist_t0                8151 non-null   float64
 129  defender3_dx_t0                  8151 non-null   float64
 130  defender3_dy_t0                  8151 non-null   float64
 131  defender3_dist_t0                8151 non-null   float64
 132  defender4_dx_t0                  8151 non-null   float64
 133  defender4_dy_t0                  8151 non-null   float64
 134  defender4_dist_t0                8151 non-null   float64
 135  defender5_dx_t0                  8151 non-null   float64
 136  defender5_dy_t0                  8151 non-null   float64
 137  defender5_dist_t0                8151 non-null   float64
 138  attacker1_dx_t0                  8151 non-null   float64
 139  attacker1_dy_t0                  8151 non-null   float64
 140  attacker1_dist_t0                8151 non-null   float64
 141  attacker2_dx_t0                  8151 non-null   float64
 142  attacker2_dy_t0                  8151 non-null   float64
 143  attacker2_dist_t0                8151 non-null   float64
 144  attacker3_dx_t0                  8151 non-null   float64
 145  attacker3_dy_t0                  8151 non-null   float64
 146  attacker3_dist_t0                8151 non-null   float64
 147  attacker4_dx_t0                  8151 non-null   float64
 148  attacker4_dy_t0                  8151 non-null   float64
 149  attacker4_dist_t0                8151 non-null   float64
 150  shooter_x_t1                     8151 non-null   float64
 151  shooter_y_t1                     8151 non-null   float64
 152  defender1_dx_t1                  8151 non-null   float64
 153  defender1_dy_t1                  8151 non-null   float64
 154  defender1_dist_t1                8151 non-null   float64
 155  defender2_dx_t1                  8151 non-null   float64
 156  defender2_dy_t1                  8151 non-null   float64
 157  defender2_dist_t1                8151 non-null   float64
 158  defender3_dx_t1                  8151 non-null   float64
 159  defender3_dy_t1                  8151 non-null   float64
 160  defender3_dist_t1                8151 non-null   float64
 161  defender4_dx_t1                  8151 non-null   float64
 162  defender4_dy_t1                  8151 non-null   float64
 163  defender4_dist_t1                8151 non-null   float64
 164  defender5_dx_t1                  8151 non-null   float64
 165  defender5_dy_t1                  8151 non-null   float64
 166  defender5_dist_t1                8151 non-null   float64
 167  attacker1_dx_t1                  8151 non-null   float64
 168  attacker1_dy_t1                  8151 non-null   float64
 169  attacker1_dist_t1                8151 non-null   float64
 170  attacker2_dx_t1                  8151 non-null   float64
 171  attacker2_dy_t1                  8151 non-null   float64
 172  attacker2_dist_t1                8151 non-null   float64
 173  attacker3_dx_t1                  8151 non-null   float64
 174  attacker3_dy_t1                  8151 non-null   float64
 175  attacker3_dist_t1                8151 non-null   float64
 176  attacker4_dx_t1                  8151 non-null   float64
 177  attacker4_dy_t1                  8151 non-null   float64
 178  attacker4_dist_t1                8151 non-null   float64
 179  shooter_x_t2                     8151 non-null   float64
 180  shooter_y_t2                     8151 non-null   float64
 181  defender1_dx_t2                  8151 non-null   float64
 182  defender1_dy_t2                  8151 non-null   float64
 183  defender1_dist_t2                8151 non-null   float64
 184  defender2_dx_t2                  8151 non-null   float64
 185  defender2_dy_t2                  8151 non-null   float64
 186  defender2_dist_t2                8151 non-null   float64
 187  defender3_dx_t2                  8151 non-null   float64
 188  defender3_dy_t2                  8151 non-null   float64
 189  defender3_dist_t2                8151 non-null   float64
 190  defender4_dx_t2                  8151 non-null   float64
 191  defender4_dy_t2                  8151 non-null   float64
 192  defender4_dist_t2                8151 non-null   float64
 193  defender5_dx_t2                  8151 non-null   float64
 194  defender5_dy_t2                  8151 non-null   float64
 195  defender5_dist_t2                8151 non-null   float64
 196  attacker1_dx_t2                  8151 non-null   float64
 197  attacker1_dy_t2                  8151 non-null   float64
 198  attacker1_dist_t2                8151 non-null   float64
 199  attacker2_dx_t2                  8151 non-null   float64
 200  attacker2_dy_t2                  8151 non-null   float64
 201  attacker2_dist_t2                8151 non-null   float64
 202  attacker3_dx_t2                  8151 non-null   float64
 203  attacker3_dy_t2                  8151 non-null   float64
 204  attacker3_dist_t2                8151 non-null   float64
 205  attacker4_dx_t2                  8151 non-null   float64
 206  attacker4_dy_t2                  8151 non-null   float64
 207  attacker4_dist_t2                8151 non-null   float64
 208  shooter_x_t3                     8151 non-null   float64
 209  shooter_y_t3                     8151 non-null   float64
 210  defender1_dx_t3                  8151 non-null   float64
 211  defender1_dy_t3                  8151 non-null   float64
 212  defender1_dist_t3                8151 non-null   float64
 213  defender2_dx_t3                  8151 non-null   float64
 214  defender2_dy_t3                  8151 non-null   float64
 215  defender2_dist_t3                8151 non-null   float64
 216  defender3_dx_t3                  8151 non-null   float64
 217  defender3_dy_t3                  8151 non-null   float64
 218  defender3_dist_t3                8151 non-null   float64
 219  defender4_dx_t3                  8151 non-null   float64
 220  defender4_dy_t3                  8151 non-null   float64
 221  defender4_dist_t3                8151 non-null   float64
 222  defender5_dx_t3                  8151 non-null   float64
 223  defender5_dy_t3                  8151 non-null   float64
 224  defender5_dist_t3                8151 non-null   float64
 225  attacker1_dx_t3                  8151 non-null   float64
 226  attacker1_dy_t3                  8151 non-null   float64
 227  attacker1_dist_t3                8151 non-null   float64
 228  attacker2_dx_t3                  8151 non-null   float64
 229  attacker2_dy_t3                  8151 non-null   float64
 230  attacker2_dist_t3                8151 non-null   float64
 231  attacker3_dx_t3                  8151 non-null   float64
 232  attacker3_dy_t3                  8151 non-null   float64
 233  attacker3_dist_t3                8151 non-null   float64
 234  attacker4_dx_t3                  8151 non-null   float64
 235  attacker4_dy_t3                  8151 non-null   float64
 236  attacker4_dist_t3                8151 non-null   float64
 237  shooter_x_t4                     8151 non-null   float64
 238  shooter_y_t4                     8151 non-null   float64
 239  defender1_dx_t4                  8151 non-null   float64
 240  defender1_dy_t4                  8151 non-null   float64
 241  defender1_dist_t4                8151 non-null   float64
 242  defender2_dx_t4                  8151 non-null   float64
 243  defender2_dy_t4                  8151 non-null   float64
 244  defender2_dist_t4                8151 non-null   float64
 245  defender3_dx_t4                  8151 non-null   float64
 246  defender3_dy_t4                  8151 non-null   float64
 247  defender3_dist_t4                8151 non-null   float64
 248  defender4_dx_t4                  8151 non-null   float64
 249  defender4_dy_t4                  8151 non-null   float64
 250  defender4_dist_t4                8151 non-null   float64
 251  defender5_dx_t4                  8151 non-null   float64
 252  defender5_dy_t4                  8151 non-null   float64
 253  defender5_dist_t4                8151 non-null   float64
 254  attacker1_dx_t4                  8151 non-null   float64
 255  attacker1_dy_t4                  8151 non-null   float64
 256  attacker1_dist_t4                8151 non-null   float64
 257  attacker2_dx_t4                  8151 non-null   float64
 258  attacker2_dy_t4                  8151 non-null   float64
 259  attacker2_dist_t4                8151 non-null   float64
 260  attacker3_dx_t4                  8151 non-null   float64
 261  attacker3_dy_t4                  8151 non-null   float64
 262  attacker3_dist_t4                8151 non-null   float64
 263  attacker4_dx_t4                  8151 non-null   float64
 264  attacker4_dy_t4                  8151 non-null   float64
 265  attacker4_dist_t4                8151 non-null   float64
 266  shooter_x_t5                     8151 non-null   float64
 267  shooter_y_t5                     8151 non-null   float64
 268  defender1_dx_t5                  8151 non-null   float64
 269  defender1_dy_t5                  8151 non-null   float64
 270  defender1_dist_t5                8151 non-null   float64
 271  defender2_dx_t5                  8151 non-null   float64
 272  defender2_dy_t5                  8151 non-null   float64
 273  defender2_dist_t5                8151 non-null   float64
 274  defender3_dx_t5                  8151 non-null   float64
 275  defender3_dy_t5                  8151 non-null   float64
 276  defender3_dist_t5                8151 non-null   float64
 277  defender4_dx_t5                  8151 non-null   float64
 278  defender4_dy_t5                  8151 non-null   float64
 279  defender4_dist_t5                8151 non-null   float64
 280  defender5_dx_t5                  8151 non-null   float64
 281  defender5_dy_t5                  8151 non-null   float64
 282  defender5_dist_t5                8151 non-null   float64
 283  attacker1_dx_t5                  8151 non-null   float64
 284  attacker1_dy_t5                  8151 non-null   float64
 285  attacker1_dist_t5                8151 non-null   float64
 286  attacker2_dx_t5                  8151 non-null   float64
 287  attacker2_dy_t5                  8151 non-null   float64
 288  attacker2_dist_t5                8151 non-null   float64
 289  attacker3_dx_t5                  8151 non-null   float64
 290  attacker3_dy_t5                  8151 non-null   float64
 291  attacker3_dist_t5                8151 non-null   float64
 292  attacker4_dx_t5                  8151 non-null   float64
 293  attacker4_dy_t5                  8151 non-null   float64
 294  attacker4_dist_t5                8151 non-null   float64
 295  shooter_speed                    8151 non-null   float64
 296  nearest_teammate_distance        8151 non-null   float64
 297  defenders_between                8151 non-null   int64
 298  has_screen                       8151 non-null   int64
 299  offensive_spacing                8151 non-null   float64
 300  teammate_between_defender        8151 non-null   int64
 301  players_in_paint                 8151 non-null   int64
dtypes: float64(247), int64(26), str(29)
memory usage: 20.6 MB

In [15]:
df.describe()

,shooter_slot,shooter_x,shooter_y,shooter_team_id,shot_angle,distance_to_basket_tracking,nearest_defender_dist,avg_defender_dist,defenders_within_3ft,defenders_within_5ft,defenders_within_7ft,offensive_spacing_area,ball_height,defender_closing_speed,ball_speed,ball_xy_speed,EVENTTIME,GAME_DATE,GAME_EVENT_ID,GAME_ID,LOC_X,LOC_Y,MINUTES_REMAINING,PERIOD,PLAYER_ID,QUARTER,SECONDS_REMAINING,SHOT_ATTEMPTED_FLAG,SHOT_DISTANCE,SHOT_MADE_FLAG,SHOT_TIME,TEAM_ID,tracking_game_clock,tracking_game_clock_old,event_GAME_ID,event_EVENTNUM,event_EVENTMSGTYPE,event_EVENTMSGACTIONTYPE,event_PERIOD,event_NEUTRALDESCRIPTION,event_PERSON1TYPE,event_PLAYER1_ID,event_PLAYER1_TEAM_ID,event_PERSON2TYPE,event_PLAYER2_ID,event_PLAYER2_TEAM_ID,event_PERSON3TYPE,event_PLAYER3_ID,event_PLAYER3_TEAM_ID,ball_x,ball_y,ball_z,player1_team_id,player1_id,player1_x,player1_y,player2_team_id,player2_id,player2_x,player2_y,player3_team_id,player3_id,player3_x,player3_y,player4_team_id,player4_id,player4_x,player4_y,player5_team_id,player5_id,player5_x,player5_y,player6_team_id,player6_id,player6_x,player6_y,player7_team_id,player7_id,player7_x,player7_y,player8_team_id,player8_id,player8_x,player8_y,player9_team_id,player9_id,player9_x,player9_y,player10_team_id,player10_id,player10_x,player10_y,shooter_x_t0,shooter_y_t0,defender1_dx_t0,defender1_dy_t0,defender1_dist_t0,defender2_dx_t0,defender2_dy_t0,defender2_dist_t0,defender3_dx_t0,defender3_dy_t0,defender3_dist_t0,defender4_dx_t0,defender4_dy_t0,defender4_dist_t0,defender5_dx_t0,defender5_dy_t0,defender5_dist_t0,attacker1_dx_t0,attacker1_dy_t0,attacker1_dist_t0,attacker2_dx_t0,attacker2_dy_t0,attacker2_dist_t0,attacker3_dx_t0,attacker3_dy_t0,attacker3_dist_t0,attacker4_dx_t0,attacker4_dy_t0,attacker4_dist_t0,shooter_x_t1,shooter_y_t1,defender1_dx_t1,defender1_dy_t1,defender1_dist_t1,defender2_dx_t1,defender2_dy_t1,defender2_dist_t1,defender3_dx_t1,defender3_dy_t1,defender3_dist_t1,defender4_dx_t1,defender4_dy_t1,defender4_dist_t1,defender5_dx_t1,defender5_dy_t1,defender5_dist_t1,attacker1_dx_t1,attacker1_dy_t1,attacker1_dist_t1,attacker2_dx_t1,attacker2_dy_t1,attacker2_dist_t1,attacker3_dx_t1,attacker3_dy_t1,attacker3_dist_t1,attacker4_dx_t1,attacker4_dy_t1,attacker4_dist_t1,shooter_x_t2,shooter_y_t2,defender1_dx_t2,defender1_dy_t2,defender1_dist_t2,defender2_dx_t2,defender2_dy_t2,defender2_dist_t2,defender3_dx_t2,defender3_dy_t2,defender3_dist_t2,defender4_dx_t2,defender4_dy_t2,defender4_dist_t2,defender5_dx_t2,defender5_dy_t2,defender5_dist_t2,attacker1_dx_t2,attacker1_dy_t2,attacker1_dist_t2,attacker2_dx_t2,attacker2_dy_t2,attacker2_dist_t2,attacker3_dx_t2,attacker3_dy_t2,attacker3_dist_t2,attacker4_dx_t2,attacker4_dy_t2,attacker4_dist_t2,shooter_x_t3,shooter_y_t3,defender1_dx_t3,defender1_dy_t3,defender1_dist_t3,defender2_dx_t3,defender2_dy_t3,defender2_dist_t3,defender3_dx_t3,defender3_dy_t3,defender3_dist_t3,defender4_dx_t3,defender4_dy_t3,defender4_dist_t3,defender5_dx_t3,defender5_dy_t3,defender5_dist_t3,attacker1_dx_t3,attacker1_dy_t3,attacker1_dist_t3,attacker2_dx_t3,attacker2_dy_t3,attacker2_dist_t3,attacker3_dx_t3,attacker3_dy_t3,attacker3_dist_t3,attacker4_dx_t3,attacker4_dy_t3,attacker4_dist_t3,shooter_x_t4,shooter_y_t4,defender1_dx_t4,defender1_dy_t4,defender1_dist_t4,defender2_dx_t4,defender2_dy_t4,defender2_dist_t4,defender3_dx_t4,defender3_dy_t4,defender3_dist_t4,defender4_dx_t4,defender4_dy_t4,defender4_dist_t4,defender5_dx_t4,defender5_dy_t4,defender5_dist_t4,attacker1_dx_t4,attacker1_dy_t4,attacker1_dist_t4,attacker2_dx_t4,attacker2_dy_t4,attacker2_dist_t4,attacker3_dx_t4,attacker3_dy_t4,attacker3_dist_t4,attacker4_dx_t4,attacker4_dy_t4,attacker4_dist_t4,shooter_x_t5,shooter_y_t5,defender1_dx_t5,defender1_dy_t5,defender1_dist_t5,defender2_dx_t5,defender2_dy_t5,defender2_dist_t5,defender3_dx_t5,defender3_dy_t5,defender3_dist_t5,defender4_dx_t5,defender4_dy_t5,defender4_dist_t5,defender5_dx_t5,defender5_dy_t5,defender5_dist_t5,attacker1_dx_t5,attacker1_dy_t5,attacker1_dist_t5,attacker2_dx_t5,attacker2_dy_t5,attacker2_dist_t5,attacker3_dx_t5,attacker3_dy_t5,attacker3_dist_t5,attacker4_dx_t5,attacker4_dy_t5,attacker4_dist_t5,shooter_speed,nearest_teammate_distance,defenders_between,has_screen,offensive_spacing,teammate_between_defender,players_in_paint
count,8151.000000,8151.000000,8151.000000,8.151000e+03,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8.151000e+03,8151.000000,8.151000e+03,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.0,8151.000000,8151.000000,8151.000000,8.151000e+03,8151.000000,8151.000000,8.151000e+03,8151.000000,8151.000000,8151.000000,8151.000000,0.0,8151.000000,8151.000000,8.151000e+03,8151.000000,8.151000e+03,1.897000e+03,8151.000000,8.151000e+03,3.540000e+02,8151.000000,8151.000000,8151.000000,8.151000e+03,8151.000000,8151.000000,8151.000000,8.151000e+03,8151.000000,8151.000000,8151.000000,8.151000e+03,8.151000e+03,8151.000000,8151.000000,8.151000e+03,8.151000e+03,8151.000000,8151.000000,8.151000e+03,8.151000e+03,8151.000000,8151.000000,8.151000e+03,8151.000000,8151.000000,8151.000000,8.151000e+03,8.151000e+03,8151.000000,8151.000000,8.151000e+03,8.151000e+03,8151.000000,8151.000000,8.151000e+03,8.151000e+03,8151.000000,8151.000000,8.151000e+03,8.151000e+03,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000,8151.000000
mean,4.999632,76.758618,25.021049,1.610613e+09,0.001771,17.307957,6.316105,16.860807,0.194209,0.478592,0.834376,383.997311,6.231680,0.612733,14.970072,12.414580,343.006993,2.015309e+07,250.491841,2.150032e+07,-3.009445,131.657708,5.237272,2.417986,117472.686542,2.418231,28.770703,1.0,12.539443,0.470985,345.231827,1.610613e+09,345.231822,345.231822,2.150032e+07,250.491841,1.529015,31.400932,2.417986,NaN,4.482640,117472.686542,1.610613e+09,1.039382,4.546415e+04,1.610613e+09,0.195927,1.143164e+04,1.610613e+09,76.073856,24.708129,6.231680,1.610613e+09,82986.667648,78.246500,25.159361,1.610613e+09,134888.682493,77.519348,24.966191,1.610613e+09,1.766979e+05,78.252670,24.914753,1.610613e+09,2.137479e+05,77.797733,24.647685,1.610613e+09,4.246434e+05,78.893044,24.776338,1.610613e+09,82768.126119,78.201664,25.051726,1.610613e+09,1.385668e+05,77.814326,24.534396,1.610613e+09,1.786611e+05,77.767369,25.076116,1.610613e+09,2.290633e+05,77.796343,24.859504,1.610613e+09,4.647697e+05,78.824888,25.118824,76.758618,25.021049,1.147314,-0.018577,6.316105,1.399119,-0.073085,12.245129,1.495731,-0.059363,17.124036,1.640443,-0.182523,21.765293,2.746518,-0.137995,26.853473,1.325281,-0.069999,12.200015,0.994986,-0.310821,18.104416,0.327800,-0.078140,23.329866,2.450518,-0.175092,29.047494,76.758618,25.021049,1.147314,-0.018577,6.316105,1.399119,-0.073085,12.245129,1.495731,-0.059363,17.124036,1.640443,-0.182523,21.765293,2.746518,-0.137995,26.853473,1.325281,-0.069999,12.200015,0.994986,-0.310821,18.104416,0.327800,-0.078140,23.329866,2.450518,-0.175092,29.047494,76.758618,25.021049,1.147314,-0.018577,6.316105,1.399119,-0.073085,12.245129,1.495731,-0.059363,17.124036,1.640443,-0.182523,21.765293,2.746518,-0.137995,26.853473,1.325281,-0.069999,12.200015,0.994986,-0.310821,18.104416,0.327800,-0.078140,23.329866,2.450518,-0.175092,29.047494,76.758618,25.021049,1.147314,-0.018577,6.316105,1.399119,-0.073085,12.245129,1.495731,-0.059363,17.124036,1.640443,-0.182523,21.765293,2.746518,-0.137995,26.853473,1.325281,-0.069999,12.200015,0.994986,-0.310821,18.104416,0.327800,-0.078140,23.329866,2.450518,-0.175092,29.047494,76.758618,25.021049,1.147314,-0.018577,6.316105,1.399119,-0.073085,12.245129,1.495731,-0.059363,17.124036,1.640443,-0.182523,21.765293,2.746518,-0.137995,26.853473,1.325281,-0.069999,12.200015,0.994986,-0.310821,18.104416,0.327800,-0.078140,23.329866,2.450518,-0.175092,29.047494,76.758618,25.021049,1.147314,-0.018577,6.316105,1.399119,-0.073085,12.245129,1.495731,-0.059363,17.124036,1.640443,-0.182523,21.765293,2.746518,-0.137995,26.853473,1.325281,-0.069999,12.200015,0.994986,-0.310821,18.104416,0.327800,-0.078140,23.329866,2.450518,-0.175092,29.047494,4.368573,12.200015,0.803828,0.038891,20.914712,0.107840,2.920991
std,2.951281,9.075436,11.215306,7.395253e+00,49.824336,8.037333,3.764178,4.581209,0.415286,0.611948,0.755057,201.085530,2.395769,4.623349,4.886366,5.459322,198.124760,3.685399e+03,160.353122,1.825999e+02,124.419024,88.531525,3.295603,1.125113,96393.733755,1.125458,17.338140,0.0,9.549298,0.499188,197.955637,7.395253e+00,197.955636,197.955636,1.825999e+02,160.353122,0.499188,34.969950,1.125113,NaN,0.499729,96393.733755,7.395253e+00,1.902609,1.521743e+05,7.560831e+00,0.925448,9.013181e+04,8.385399e+00,8.862460,12.453154,2.395769,8.272215e+00,94225.234178,9.041009,11.979266,8.272215e+00,88304.180823,9.328238,11.911275,8.272215e+00,9.310982e+04,9.102985,12.069905,8.272215e+00,1.580550e+05,9.276012,12.270994,8.272215e+00,5.162437e+05,8.868623,11.267781,8.207577e+00,93831.878571,9.053355,12.180975,8.207577e+00,9.090908e+04,9.170480,12.059595,8.207577e+00,1.037682e+05,9.356066,12.287452,8.207577e+00,2.146337e+05,9.252207,12.248210,8.207577e+00,5.521060e+05,9.112672,11.182482,9.075436,11.215306,4.996590,5.271088,3.764178,9.209791,9.444435,5.100896,12.014001,13.334157,5.577486,14.015521,17.670472,6.133434,15.225092,22.979956,6.800562,9.095462,9.887345,5.778398,12.480303,14.588613,6.470104,14.597760,19.657916,7.435887,15.155468,26.063128,8.435095,9.075436,11.215306,4.996590,5.271088,3.764178,9.209791,9.444435,5.100896,12.014001,13.334157,5.577486,14.015521,17.670472,6.133434,15.225092,22.979956,6.800562,9.095462,9.887345,5.778398,12.480303,14.588613,6.470104,14.597760,19.657916,7.435887,15.155468,26.063128,8.435095,9.075436,11.215306,4.996590,5.271088,3.764178,9.209791,9.444435,5.100896,12.014001,13.334157,5.577486,14.015521,17.670472,6.133434,15.225092,22.979956,6.800562,9.095462,9.887345,5.778398,12.480303,14.588613,6.470104,14.597760,19.657916,7.435887,15.155468,26.063128,8.435095,9.075436,11.215306,4.996590,5.271088,3.764178,9.209791,9.444435,5.100896,12.014001,13.334157,5.577486,14.015521,17.670472,6.133434,15.225092,22.979956,6.800562,9.095462,9.887345,5.778398,12.480303,14.588613,6.470104,14.597760,19.657916,7.435887,15.155468,26.063128,8.435095,9.075436,11.215306,4.996590,5.271088,3.764178,9.209791,9.444435,5.100896,12.014001,13.334157,5.577486,14.015521,17.670472,6.133434,15.225092,22.979956,6.800562,9.095462,9.887345,5.778398,12.480303,14.588613,6.470104,14.597760,19.657916,7.435887,15.155468,26.063128,8.435095,9.075436,11.215306,4.996590,5.271088,3.764178,9.209791,9.444435,5.100896,12.014001,13.334157,5.577486,14.015521,17.670472,6.133434,15.225092,22.979956,6.800562,9.095462,9.887345,5.778398,12.480303,14.588613,6.470104,14.597760,19.657916,7.435887,15.155468,26.063128,8.435095,4.219556,5.778398,0.761925,0.193347,5.448232,0.310197,1.557295
min,1.000000,47.015280,-0.876100,1.610613e+09,-177.823064,0.213762,0.000000,3.631695,0.000000,0.000000,0.000000,19.673588,0.048150,-26.760097,0.478086,0.261443,0.000000,2.015103e+07,2.000000,2.150000e+07,-246.456400,-87.352600,0.000000,1.000000,708.000000,1.000000,0.000000,1.0,0.000000,0.000000,0.410000,1.610613e+09,0.410000,0.410000,2.150000e+07,2.000000,1.000000,0.000000,1.000000,NaN,4.000000,708.000000,1.610613e+09,0.000000,0.000000e+00,1.610613e+09,0.000000,0.000000e+00,1.610613e+09,47.094900,0.354360,0.048150,1.610613e+09,708.000000,47.200100,-1.799210,1.610613e+09,1889.000000,47.097880,-1.097260,1.610613e+09,2.225000e+03,47.019360,-1.553250,1.610613e+09,2.561000e+03,47.112150,-0.170660,1.610613e+09,2.585000e+03,47.021190,-2.064640,1.610613e+09,708.000000,47.087030,-2.563930,1.610613e+09,1.897000e+03,47.015280,-0.763140,1.610613e+09,2.225000e+03,47.013020,-1.325280,1.610613e+09,2.446000e+03,47.041820,-0.424300,1.610613e+09,2.564000e+03,47.283400,-2.481390,47.015280,-0.876100,-22.332950,-23.501860,0.000000,-30.565360,-29.220250,1.391599,-36.455680,-33.793030,2.619561,-37.034320,-38.858760,3.899942,-45.071680,-44.598450,6.982148,-30.495080,-37.013880,0.000000,-33.354430,-42.761860,2.853404,-43.045730,-46.703820,5.037123,-46.994010,-47.402080,7.496455,47.015280,-0.876100,-22.332950,-23.501860,0.000000,-30.565360,-29.220250,1.391599,-36.455680,-33.793030,2.619561,-37.034320,-38.858760,3.899942,-45.071680,-44.598450,6.982148,-30.495080,-37.013880,0.000000,-33.354430,-42.761860,2.853404,-43.045730,-46.703820,5.037123,-46.994010,-47.402080,7.496455,47.015280,-0.876100,-22.332950,-23.501860,0.000000,-30.565360,-29.220250,1.391599,-36.455680,-33.793030,2.619561,-37.034320,-38.858760,3.899942,-45.071680,-44.598450,6.982148,-30.495080,-37.013880,0.000000,-33.354430,-42.761860,2.853404,-43.045730,-46.703820,5.037123,-46.994010,-47.402080,7.496455,47.015280,-0.876100,-22.332950,-23.501860,0.000000,-30.565360,-29.220250,1.391599,-36.455680,-33.793030,2.619561,-37.034320,-38.858760,3.899942,-45.071680,-44.598450,6.982148,-30.495080,-37.013880,0.000000,-33.354430,-42.761860,2.853404,-43.045730,-46.703820,5.037123,-46.994010,-47.402080,7.496455,47.015280,-0.876100,-22.332950,-23.501860,0.000000,-30.565360,-29.220250,1.391599,-36.455680,-33.793030,2.619561,-37.034320,-38.858760,3.899942,-45.071680,-44.598450,6.982148,-30.495080,-37.013880,0.000000,-33.354430,-42.761860,2.853404,-43.045730,-46.703820,5.037123,-46.994010,-47.402080,7.496455,47.015280,-0.876100,-22.332950,-23.501860,0.000000,-30.565360,-29.220250,1.391599,-36.455680,-33.793030,2.619561,-37.034320,-38.858760,3.899942,-45.071680,-44.598450,6.982148,-30.495080,-37.013880,0.000000,-33.354430,-42.761860,2.853404,-43.045730,-46.703820,5.037123,-46.994010,-47.402080,7.496455,0.016465,0.000000,0.000000,0.000000,5.873597,0.000000,0.000000
25%,2.000000,70.300960,16.848150,1.610613e+09,-36.806282,10.949192,3.587993,13.926917,0.000000,0.000000,0.000000,207.634016,4.530255,-2.254327,11.985017,8.569061,180.000000,2.015112e+07,96.000000,2.150018e+07,-97.601100,56.600550,3.000000,1.000000,2225.000000,1.000000,13.000000,1.0,2.000000,0.000000,181.620000,1.610613e+09,181.620000,181.620000,2.150018e+07,96.000000,1.000000,1.000000,1.000000,NaN,4.000000,2225.000000,1.610613e+09,0.000000,0.000000e+00,1.610613e+09,0.000000,0.000000e+00,1.610613e+09,68.933910,15.239890,4.530255,1.610613e+09,2200.000000,72.206850,16.391160,1.610613e+09,2754.000000,71.264830,16.247540,1.610613e+09,2.011420e+05,72.160660,15.978970,1.610613e+09,2.019390e+05,71.576585,15.497740,1.610613e+09,2.026950e+05,73.134140,16.826310,1.610613e+09,2210.000000,72.031270,16.045795,1.610613e+09,2.756000e+03,71.564935,15.539580,1.610613e+09,2.008260e+05,71.218140,16.165685,1.610613e+09,2.019360e+05,71.644990,15.795185,1.610613e+09,2.026950e+05,73.035085,17.487340,70.300960,16.848150,-1.731105,-3.188450,3.587993,-5.327240,-7.235050,8.379124,-7.620870,-11.477340,13.190374,-9.037745,-16.208655,17.822002,-7.596780,-22.027510,22.383548,-4.914355,-7.217790,7.818088,-8.531580,-12.111385,13.199612,-11.037955,-17.089895,17.685322,-7.873785,-24.150055,22.732832,70.300960,16.848150,-1.731105,-3.188450,3.587993,-5.327240,-7.235050,8.379124,-7.620870,-11.477340,13.190374,-9.037745,-16.208655,17.822002,-7.596780,-22.027510,22.383548,-4.914355,-7.217790,7.818088,-8.531580,-12.111385,13.199612,-11.037955,-17.089895,17.685322,-7.873785,-24.150055,22.732832,70.300960,16.848150,-1.731105,-3.188450,3.587993,-5.327240,-7.235050,8.379124,-7.620870,-11.477340,13.190374,-9.037745,-16.208655,17.822002,-7.596780,-22.027510,22.383548,-4.914355,-7.217790,7.818088,-8.531580,-12.111385,13.199612,-11.037955,-17.089895,17.685322,-7.873785,-24.150055,22.732832,70.300960,16.848150,-1.731105,-3.188450,3.587993,-5.327240,-7.235050,8.379124,-7.620870,-11.477340,13.190374,-9.037745,-16.208655,17.822002,-7.596780,-22.027510,22.383548,-4.914355,-7.217790,7.818088,-8.531580,-12.111385,13.199612,-11.037955,-17.089895,17.685322,-7.873785,-24.150055,22.732832,70.300960,16.848150,-1.731105,-3.188450,3.587993,-5.327240,-7.235050,8.379124,-7.620870,-11.477340,13.190374,-9.037745,-16.208655,17.822002,-7.596780,-22.027510,22.383548,-4.914355,-7.217790,7.818088,-8.531580,-12.111385,13.199612,-11.037955,-17.089895,17.685322,-7.873785,-24.150055,22.732832,70.300960,16.848150,-1.731105,-3.188450,3.587993,-5.327240,-7.235050,8.379124,-7.620870,-11.477340,13.190374,-9.037745,-16.208655,17.822002,-7.596780,-22.027510,22.383548,-4.914355,-7.217790,7.818088,-8.531580,-12.111385,13.199612,-11.037955,-17.089895,17.685322,-7.873785,-24.150055,22.732832,1.692536,7.818088,0.000000,0.000000,15.988816,0.000000,2.000000

In [16]:
df.to_csv('merged_filtered_prep_20_players_v2.csv')
#df.to_csv('merged_filtered_prep_all_players_v2.csv')

In [17]:
df = pd.read_csv('merged_filtered_prep_20_players_v2.csv')
#df = pd.read_csv('merged_filtered_prep_all_players_v2.csv')

In [18]:
df.shape

(8151, 303)

## Train test split of new and old data

In [19]:
# Load old dataset to make the same datasplit on both datasets
from app.data_providers import test_train_dataset
data = test_train_dataset()
X_train = data['train'].drop('SHOT_MADE_FLAG', axis=1)
y_train = data['train']['SHOT_MADE_FLAG']

X_test = data['test'].drop('SHOT_MADE_FLAG', axis=1)
y_test = data['test']['SHOT_MADE_FLAG']

df_old = pd.concat([data['train'], data['test']], axis=0)

Repo card metadata block was not found. Setting CardData to empty.

In [20]:
# GAME_DATE to year, for filtering
df_old['GAME_DATE'] = pd.to_datetime(df_old['GAME_DATE'].astype(int).astype(str),format='%Y%m%d')
df_old['year'] = df_old['GAME_DATE'].dt.year
df_old.head()

,GAME_ID_x,GAME_EVENT_ID,SHOT_TYPE,SHOT_DISTANCE,SHOT_ZONE_RANGE,SHOT_ZONE_BASIC,SHOT_ZONE_AREA,LOC_X,LOC_Y,ACTION_TYPE,HTM,VTM,GAME_DATE,TEAM_ID,PLAYER1_TEAM_ABBREVIATION,PLAYER_ID,scoreHome,scoreAway,shotResult,MINUTES_REMAINING,SECONDS_REMAINING,clock,PLAYER_NAME,PERIOD_x,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ABBREVIATION,PLAYER3_ID,PLAYER3_NAME,is_playoffs,PCTIMESTRING,SHOT_MADE_FLAG,IS_HOME,points,pointsHome,pointsAway,scoreHomeBeforeShot,scoreAwayBeforeShot,scoreMargin,scoreMarginBeforeShot,TimeRemainingInPeriod,TotalPlayedTime,TimeRemainingInGame,IsOvertime,OvertimeNumber,IsClutchTime,OPPONENT_INTERFERED,ANGLE,ANGLE_SECTOR,ABS_ANGLE,ANGLE_SIN,ANGLE_COS,MAIN_ACTION_TYPE,__index_level_0__,year
0,29600008.0,281.0,2PT Field Goal,8.0,8-16 ft.,In The Paint (Non-RA),Left Side(L),-42.0,69.0,Jump Shot,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,50,44,Missed,5.0,25.0,PT05M25.00S,Kevin Garnett,3.0,0.0,NaN,NaN,0.0,NaN,False,5:25,0.0,1,2,0,0,50.0,44.0,6,6.0,325,1835,1045,0,0,0,False,-31.328693,0,31.328693,0.087123,0.996198,Jump,448756,1996
1,29600008.0,168.0,1PT Free Throw,15.0,8-16 ft.,Mid-Range,Center(C),0.0,15.0,Free Throw,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,27,31,Missed,6.0,31.0,PT06M31.00S,Kevin Garnett,2.0,0.0,NaN,NaN,0.0,NaN,False,6:31,0.0,1,1,0,0,27.0,31.0,-4,-4.0,391,1049,1831,0,0,0,False,0.000000,0,0.000000,0.000000,1.000000,Other,448749,1996
2,29600008.0,404.0,2PT Field Goal,12.0,8-16 ft.,Mid-Range,Right Side(R),112.0,58.0,Jump Shot,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,71,70,Missed,2.0,53.0,PT02M53.00S,Kevin Garnett,4.0,0.0,NaN,NaN,0.0,NaN,False,2:53,0.0,1,2,0,0,71.0,70.0,1,1.0,173,2707,173,0,0,1,False,62.622297,1,62.622297,-0.208025,0.978123,Jump,448762,1996
3,29600008.0,206.0,2PT Field Goal,14.0,8-16 ft.,Mid-Range,Right Side(R),140.0,-5.0,Jump Shot,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,35,34,Missed,3.0,13.0,PT03M13.00S,Kevin Garnett,2.0,0.0,NaN,NaN,0.0,NaN,False,3:13,0.0,1,2,0,0,35.0,34.0,1,1.0,193,1247,1633,0,0,0,False,92.045408,2,92.045408,-0.807099,-0.590417,Jump,448751,1996
4,29600008.0,260.0,2PT Field Goal,16.0,16-24 ft.,Mid-Range,Right Side(R),151.0,67.0,Jump Shot,MIN,SAS,1996-11-01,1.610613e+09,MIN,708.0,48,42,Missed,7.0,45.0,PT07M45.00S,Kevin Garnett,3.0,0.0,NaN,NaN,0.0,NaN,False,7:45,0.0,1,2,0,0,48.0,42.0,6,6.0,465,1695,1185,0,0,0,False,66.072727,1,66.072727,-0.099118,-0.995076,Jump,448754,1996

In [21]:
def create_match_key(df, id_cols):
    '''Create a key to match old and new games'''

    match_col = df[id_cols[0]].astype(int).astype(str) + "_"
    
    for id_col in id_cols[1:]:
        match_col = match_col + df[id_col].astype(int).astype(str) + "_"

    return match_col

df_old["match_key"] = create_match_key(df_old, ['GAME_ID_x', 'GAME_EVENT_ID'])
df["match_key"] = create_match_key(df, ['GAME_ID', 'GAME_EVENT_ID'])


old_keys = set(df_old["match_key"])
new_keys = set(df["match_key"])

intersection = old_keys & new_keys

print("OLD events:", len(old_keys))
print("NEW events:", len(new_keys))
print("OVERLAP:", len(intersection))

coverage_old = len(intersection) / len(old_keys)
coverage_new = len(intersection) / len(new_keys)

print("Coverage old -> new:", coverage_old)
print("Coverage new -> old:", coverage_new)

missing_keys = old_keys - new_keys
missing_df = df_old[df_old["match_key"].isin(missing_keys)]

C:\Users\jonas\AppData\Local\Temp\ipykernel_14492\957184064.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["match_key"] = create_match_key(df, ['GAME_ID', 'GAME_EVENT_ID'])

OLD events: 537909
NEW events: 8151
OVERLAP: 8150
Coverage old -> new: 0.015151261644627623
Coverage new -> old: 0.9998773156667894

# Filter old and new dataframes by overlapping columns and make the same train test split for both

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
if do_filter_for_players:
    df_old["match_key"] = create_match_key(df_old, ['GAME_ID_x', 'GAME_EVENT_ID'])
    df["match_key"] = create_match_key(df, ['GAME_ID', 'GAME_EVENT_ID'])
else:
    # Only based on game id, since old data was filtered by players
    df_old["match_key"] = create_match_key(df_old, ['GAME_ID_x'])
    df["match_key"] = create_match_key(df, ['GAME_ID'])

common_uids = set(df_old["match_key"]).intersection(set(df["match_key"]))

df_old_filt = df_old[df_old["match_key"].isin(common_uids)].copy().sort_values("match_key").reset_index(drop=True)
df_new_filt = df[df["match_key"].isin(common_uids)].copy().sort_values("match_key").reset_index(drop=True)

In [24]:
df_new_filt.shape

(8150, 304)

In [26]:
# Make the same split on old and new data
uids = df_old["match_key"].drop_duplicates()

train_uids, test_uids = train_test_split(
    uids,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

train_old = df_old_filt[df_old_filt["match_key"].isin(train_uids)].copy()
test_old  = df_old_filt[df_old_filt["match_key"].isin(test_uids)].copy()

train_new = df_new_filt[df_new_filt["match_key"].isin(train_uids)].copy()
test_new  = df_new_filt[df_new_filt["match_key"].isin(test_uids)].copy()

train_old.to_parquet("train_old_v2.parquet", index=False)
test_old.to_parquet("test_old_v2.parquet", index=False)

train_new.to_parquet("train_new_20_players_v2.parquet", index=False)
test_new.to_parquet("test_new_20_players_v2.parquet", index=False)

#train_new.to_parquet("train_new_all_players_v2.parquet", index=False)
#test_new.to_parquet("test_new_all_players_v2.parquet", index=False)

In [ ]:
train_new.info()